inherited ChartPrintOptions: TChartPrintOptions
  Left = 292
  Top = 168
  HelpContext = 61000
  ActiveControl = CBPrinters
  Caption = 'Chart Print Options'
  ClientHeight = 485
  ClientWidth = 651
  ParentFont = True
  KeyPreview = True
  OldCreateOrder = True
  Position = poScreenCenter
  ExplicitLeft = 292
  ExplicitTop = 168
  ExplicitWidth = 659
  ExplicitHeight = 512
  PixelsPerInch = 96
  TextHeight = 13
  inherited lblSkingroupMsg: TLabel
    Top = 485
    Width = 651
    ExplicitTop = 485
    ExplicitWidth = 651
    HelpContext = 61033
  end
  object SubForm: TDNMPanel [1]
    Left = 0
    Top = 0
    Width = 651
    Height = 485
    HelpContext = 61001
    Align = alClient
    BevelOuter = bvNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    Transparent = False
    object TeePreviewPanel1: TTeePreviewPanel
      Left = 112
      Top = 38
      Width = 539
      Height = 447
      HelpContext = 61002
      Panel = ChartDesigner.DBChart1
      Shadow.Color = clGray
      Shadow.HorizSize = 4
      Shadow.VertSize = 4
      OnChangeMargins = TeePreviewPanel1ChangeMargins
      Gradient.Direction = gdFromTopLeft
      Gradient.EndColor = clGray
      Gradient.Visible = True
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
    end
    object Panel1: TDNMPanel
      Left = 0
      Top = 0
      Width = 651
      Height = 38
      HelpContext = 61003
      Align = alTop
      BevelOuter = bvNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnResize = Panel1Resize
      object Label1: TLabel
        Left = 36
        Top = 12
        Width = 42
        Height = 15
        HelpContext = 61004
        Alignment = taRightJustify
        Caption = 'P&rinter:'
        Transparent = True
        Layout = tlCenter
      end
      object Panel3: TDNMPanel
        Left = 479
        Top = 0
        Width = 172
        Height = 38
        HelpContext = 61005
        Align = alRight
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
        object BSetupPrinter: TDNMSpeedButton
          Left = 8
          Top = 7
          Width = 75
          Height = 25
          HelpContext = 61006
          Caption = '&Setup...'
          Color = clWhite
          DisableTransparent = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          HotTrackColor = clBtnShadow
          HotTrackFont.Charset = DEFAULT_CHARSET
          HotTrackFont.Color = clWindowText
          HotTrackFont.Height = -11
          HotTrackFont.Name = 'MS Sans Serif'
          HotTrackFont.Style = []
          ParentColor = False
          ParentFont = False
          SlowDecease = True
          Style = bsModern
          TabOrder = 0
          OnClick = BSetupPrinterClick
        end
        object BPrint: TDNMSpeedButton
          Left = 94
          Top = 7
          Width = 75
          Height = 25
          HelpContext = 61007
          Caption = '&Print'
          Color = clWhite
          DisableTransparent = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          HotTrackColor = clBtnShadow
          HotTrackFont.Charset = DEFAULT_CHARSET
          HotTrackFont.Color = clWindowText
          HotTrackFont.Height = -11
          HotTrackFont.Name = 'MS Sans Serif'
          HotTrackFont.Style = []
          ParentColor = False
          ParentFont = False
          SlowDecease = True
          Style = bsModern
          TabOrder = 1
          OnClick = BPrintClick
        end
      end
      object CBPrinters: TwwDBComboBox
        Left = 79
        Top = 8
        Width = 156
        Height = 23
        HelpContext = 61008
        ShowButton = True
        Style = csDropDownList
        MapList = False
        AllowClearKey = False
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ItemHeight = 15
        ParentFont = False
        Sorted = False
        TabOrder = 0
        UnboundDataType = wwDefault
        OnChange = CBPrintersChange
      end
    end
    object Panel2: TDNMPanel
      Left = 0
      Top = 38
      Width = 112
      Height = 447
      HelpContext = 61009
      Align = alLeft
      BevelOuter = bvNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      object PanelMargins: TDNMPanel
        Left = 0
        Top = 161
        Width = 112
        Height = 58
        HelpContext = 61010
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 4
        object Label9: TLabel
          Left = 25
          Top = 36
          Width = 77
          Height = 15
          HelpContext = 61011
          Caption = '&View Margins'
          Transparent = True
        end
        object BReset: TDNMSpeedButton
          Left = 4
          Top = 5
          Width = 101
          Height = 25
          HelpContext = 61012
          Caption = 'Reset &Margins'
          Color = clWhite
          DisableTransparent = False
          Enabled = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          HotTrackColor = clBtnShadow
          HotTrackFont.Charset = DEFAULT_CHARSET
          HotTrackFont.Color = clWindowText
          HotTrackFont.Height = -11
          HotTrackFont.Name = 'MS Sans Serif'
          HotTrackFont.Style = []
          ParentColor = False
          ParentFont = False
          SlowDecease = True
          Style = bsModern
          TabOrder = 0
          OnClick = BResetClick
        end
        object ShowMargins: TwwCheckBox
          Left = 7
          Top = 36
          Width = 16
          Height = 15
          HelpContext = 61013
          DisableThemes = False
          AlwaysTransparent = False
          Frame.Transparent = True
          ValueChecked = 'True'
          ValueUnchecked = 'False'
          DisplayValueChecked = 'True'
          DisplayValueUnchecked = 'False'
          NullAndBlankState = cbUnchecked
          Caption = '&View Margins'
          Checked = True
          State = cbChecked
          TabOrder = 1
          OnClick = ShowMarginsClick
        end
      end
      object Panel4: TDNMPanel
        Left = 0
        Top = 285
        Width = 112
        Height = 162
        HelpContext = 61014
        Align = alClient
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 3
        object Label4: TLabel
          Left = 27
          Top = 7
          Width = 70
          Height = 15
          HelpContext = 61015
          Caption = 'Proport&ional'
          Transparent = True
        end
        object Label5: TLabel
          Left = 27
          Top = 28
          Width = 44
          Height = 15
          HelpContext = 61016
          Caption = 'S&mooth'
          Transparent = True
        end
        object CBProp: TwwCheckBox
          Left = 10
          Top = 5
          Width = 14
          Height = 17
          HelpContext = 61017
          DisableThemes = False
          AlwaysTransparent = False
          ValueChecked = 'True'
          ValueUnchecked = 'False'
          DisplayValueChecked = 'True'
          DisplayValueUnchecked = 'False'
          NullAndBlankState = cbUnchecked
          Caption = 'Proport&ional'
          Checked = True
          State = cbChecked
          TabOrder = 0
          OnClick = CBPropClick
        end
        object CheckBox1: TwwCheckBox
          Left = 10
          Top = 26
          Width = 15
          Height = 17
          HelpContext = 61018
          DisableThemes = False
          AlwaysTransparent = False
          ValueChecked = 'True'
          ValueUnchecked = 'False'
          DisplayValueChecked = 'True'
          DisplayValueUnchecked = 'False'
          NullAndBlankState = cbUnchecked
          Caption = 'S&mooth'
          TabOrder = 1
          OnClick = CheckBox1Click
        end
      end
      object Orientation: TwwRadioGroup
        Left = 0
        Top = 0
        Width = 112
        Height = 66
        HelpContext = 61019
        DisableThemes = False
        TransparentActiveItem = True
        Frame.Transparent = True
        Transparent = True
        Align = alTop
        Caption = 'Orien&tation:'
        Color = clBtnFace
        Items.Strings = (
          'P&ortrait'
          '&Landscape')
        ParentColor = False
        TabOrder = 0
        TabStop = False
        OnClick = OrientationClick
      end
      object GBMargins: TAdvGroupBox
        Left = 0
        Top = 66
        Width = 112
        Height = 95
        HelpContext = 61020
        Transparent = False
        Align = alTop
        Caption = 'Margins (%)'
        ParentCtl3D = True
        TabOrder = 1
        object SETopMa: TEdit
          Left = 34
          Top = 17
          Width = 27
          Height = 23
          HelpContext = 61021
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 32767
          ParentFont = False
          TabOrder = 0
          Text = '0'
          OnChange = SETopMaChange
        end
        object SELeftMa: TEdit
          Left = 6
          Top = 43
          Width = 26
          Height = 23
          HelpContext = 61022
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 32767
          ParentFont = False
          TabOrder = 1
          Text = '0'
          OnChange = SELeftMaChange
        end
        object SEBotMa: TEdit
          Left = 34
          Top = 68
          Width = 27
          Height = 23
          HelpContext = 61023
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 32767
          ParentFont = False
          TabOrder = 2
          Text = '0'
          OnChange = SEBotMaChange
        end
        object SERightMa: TEdit
          Left = 58
          Top = 43
          Width = 27
          Height = 23
          HelpContext = 61024
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = []
          MaxLength = 32767
          ParentFont = False
          TabOrder = 3
          Text = '0'
          OnChange = SERightMaChange
        end
        object UDLeftMa: TUpDown
          Left = 32
          Top = 43
          Width = 15
          Height = 23
          HelpContext = 61025
          Associate = SELeftMa
          Increment = 5
          TabOrder = 4
        end
        object UDTopMa: TUpDown
          Left = 61
          Top = 17
          Width = 15
          Height = 23
          HelpContext = 61026
          Associate = SETopMa
          Increment = 5
          TabOrder = 5
        end
        object UDRightMa: TUpDown
          Left = 85
          Top = 43
          Width = 15
          Height = 23
          HelpContext = 61027
          Associate = SERightMa
          Increment = 5
          TabOrder = 6
        end
        object UDBotMa: TUpDown
          Left = 61
          Top = 68
          Width = 15
          Height = 23
          HelpContext = 61028
          Associate = SEBotMa
          Increment = 5
          TabOrder = 7
        end
      end
      object ChangeDetailGroup: TAdvGroupBox
        Left = 0
        Top = 219
        Width = 112
        Height = 66
        HelpContext = 61029
        Transparent = False
        Align = alTop
        Caption = 'Detail:'
        Color = clBtnFace
        ParentColor = False
        ParentCtl3D = True
        TabOrder = 2
        object Label2: TLabel
          Left = 6
          Top = 16
          Width = 29
          Height = 15
          HelpContext = 61030
          Caption = 'More'
          Transparent = True
          Layout = tlCenter
        end
        object Label3: TLabel
          Left = 61
          Top = 16
          Width = 41
          Height = 15
          HelpContext = 61031
          Alignment = taRightJustify
          Caption = 'Normal'
          Transparent = True
          Layout = tlCenter
        end
        object Resolution: TAdvTrackBar
          Left = 6
          Top = 33
          Width = 100
          Height = 24
          HelpContext = 61032
          BorderColor = clNone
          BorderColorDisabled = clNone
          Buttons.BorderColor = 9262895
          Buttons.BorderColorHot = 10079963
          Buttons.BorderColorDown = 4548219
          Buttons.Color = 15653832
          Buttons.ColorTo = 16178633
          Buttons.ColorHot = 15465983
          Buttons.ColorHotTo = 11332863
          Buttons.ColorDown = 7778289
          Buttons.ColorDownTo = 4296947
          Buttons.ColorMirror = 15586496
          Buttons.ColorMirrorTo = 16245200
          Buttons.ColorMirrorHot = 5888767
          Buttons.ColorMirrorHotTo = 10807807
          Buttons.ColorMirrorDown = 946929
          Buttons.ColorMirrorDownTo = 5021693
          Buttons.GradientMirror = ggVertical
          ColorTo = clNone
          ColorDisabled = clNone
          ColorDisabledTo = clNone
          Direction = gdHorizontal
          Color = clNone
          Max = 100
          PageSize = 2
          Position = 99
          Slider.BorderColor = clGray
          Slider.BorderColorDisabled = clBlack
          Slider.Color = clWhite
          Slider.ColorTo = clBlack
          Slider.ColorDisabled = clBlack
          Slider.ColorDisabledTo = clBlack
          Slider.ColorCompleted = clNone
          Slider.ColorCompletedTo = clNone
          Slider.ColorCompletedDisabled = clNone
          Slider.ColorCompletedDisabledTo = clNone
          Slider.Direction = gdHorizontal
          TabOrder = 0
          Thumb.BorderColor = clBlack
          Thumb.BorderColorHot = 10079963
          Thumb.BorderColorDown = 4548219
          Thumb.BorderColorDisabled = clBlack
          Thumb.Color = clSilver
          Thumb.ColorTo = clSilver
          Thumb.ColorDown = 7778289
          Thumb.ColorDownTo = 4296947
          Thumb.ColorHot = 15465983
          Thumb.ColorHotTo = 11332863
          Thumb.ColorDisabled = clBlack
          Thumb.ColorDisabledTo = clBlack
          Thumb.ColorMirror = clSilver
          Thumb.ColorMirrorTo = 16245200
          Thumb.ColorMirrorHot = 5888767
          Thumb.ColorMirrorHotTo = 10807807
          Thumb.ColorMirrorDown = 946929
          Thumb.ColorMirrorDownTo = 5021693
          Thumb.ColorMirrorDisabled = clBlack
          Thumb.ColorMirrorDisabledTo = clBlack
          Thumb.Gradient = ggVertical
          Thumb.GradientMirror = ggRadial
          Thumb.Shape = tsPointer
          TickMark.Color = clBlack
          TickMark.ColorDisabled = clBlack
          TickMark.Font.Charset = DEFAULT_CHARSET
          TickMark.Font.Color = clWindowText
          TickMark.Font.Height = -11
          TickMark.Font.Name = 'Tahoma'
          TickMark.Font.Style = []
          TickMark.ShowImageAtSteps = 10
          TickMark.Spacing = 5
          TickMark.Size = 5
          TrackHint = False
          TrackLabel.Font.Charset = DEFAULT_CHARSET
          TrackLabel.Font.Color = clWindowText
          TrackLabel.Font.Height = -11
          TrackLabel.Font.Name = 'Tahoma'
          TrackLabel.Font.Style = []
          TrackLabel.Format = 'Pos: %d'
          Version = '1.6.2.0'
          OnChange = ResolutionChange
        end
      end
    end
  end
end
