object fmButtonArray: TfmButtonArray
  Left = 0
  Top = 0
  Caption = 'fmButtonArray'
  ClientHeight = 324
  ClientWidth = 393
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 16
  object pnlButtonArray: TPanel
    Left = 0
    Top = 0
    Width = 393
    Height = 324
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitLeft = 144
    ExplicitTop = 88
    ExplicitWidth = 185
    ExplicitHeight = 41
    object pnlOptions: TPanel
      Left = 0
      Top = 289
      Width = 393
      Height = 35
      Align = alBottom
      BevelOuter = bvNone
      TabOrder = 0
      ExplicitTop = 283
      ExplicitWidth = 427
      object btnCustomise: TAdvSmoothButton
        Left = 72
        Top = 1
        Width = 120
        Height = 35
        Action = actCustomise
        Status.Caption = '0'
        Status.Appearance.Fill.Color = clRed
        Status.Appearance.Fill.ColorMirror = clNone
        Status.Appearance.Fill.ColorMirrorTo = clNone
        Status.Appearance.Fill.GradientType = gtSolid
        Status.Appearance.Fill.BorderColor = clGray
        Status.Appearance.Fill.Rounding = 0
        Status.Appearance.Fill.ShadowOffset = 0
        Status.Appearance.Font.Charset = DEFAULT_CHARSET
        Status.Appearance.Font.Color = clWhite
        Status.Appearance.Font.Height = -11
        Status.Appearance.Font.Name = 'Tahoma'
        Status.Appearance.Font.Style = []
        TabOrder = 0
        Version = '1.6.9.2'
      end
      object btnHome: TAdvSmoothButton
        Left = 190
        Top = 1
        Width = 120
        Height = 35
        Action = actHome
        Status.Caption = '0'
        Status.Appearance.Fill.Color = clRed
        Status.Appearance.Fill.ColorMirror = clNone
        Status.Appearance.Fill.ColorMirrorTo = clNone
        Status.Appearance.Fill.GradientType = gtSolid
        Status.Appearance.Fill.BorderColor = clGray
        Status.Appearance.Fill.Rounding = 0
        Status.Appearance.Fill.ShadowOffset = 0
        Status.Appearance.Font.Charset = DEFAULT_CHARSET
        Status.Appearance.Font.Color = clWhite
        Status.Appearance.Font.Height = -11
        Status.Appearance.Font.Name = 'Tahoma'
        Status.Appearance.Font.Style = []
        TabOrder = 1
        Version = '1.6.9.2'
      end
    end
    object pnlButtons: TPanel
      Left = 0
      Top = 0
      Width = 393
      Height = 289
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 1
      ExplicitLeft = 112
      ExplicitTop = 184
      ExplicitWidth = 185
      ExplicitHeight = 41
    end
  end
  object ActionList1: TActionList
    Left = 24
    Top = 16
    object actCustomise: TAction
      Caption = 'Customise'
      OnExecute = actCustomiseExecute
    end
    object actHome: TAction
      Caption = 'Home'
    end
  end
end
