inherited fmCalculator: TfmCalculator
  Left = 986
  Top = 245
  HelpContext = 1218002
  BorderStyle = bsDialog
  Caption = 'Calculator'
  ClientHeight = 407
  ClientWidth = 260
  KeyPreview = True
  Position = poMainFormCenter
  OnKeyPress = FormKeyPress
  OnKeyUp = FormKeyUp
  ExplicitWidth = 266
  ExplicitHeight = 435
  PixelsPerInch = 96
  TextHeight = 13
  inherited lblSkingroupMsg: TLabel
    Top = 407
    Width = 260
    HelpContext = 1218003
    ExplicitTop = 277
    ExplicitWidth = 211
  end
  inherited shapehint: TShape
    Left = 58
    Top = 322
    ExplicitLeft = 58
    ExplicitTop = 322
  end
  inherited shapehintextra1: TShape
    Left = 98
    Top = 322
    ExplicitLeft = 98
    ExplicitTop = 322
  end
  object Panel1: TDNMPanel [3]
    Left = 0
    Top = 0
    Width = 260
    Height = 82
    HelpContext = 1218004
    Align = alTop
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentColor = True
    ParentFont = False
    TabOrder = 0
    Transparent = False
    object Equals: TLabel
      AlignWithMargins = True
      Left = 226
      Top = 58
      Width = 30
      Height = 24
      HelpContext = 1218005
      Align = alClient
      Alignment = taRightJustify
      Caption = '0.0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMaroon
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      Layout = tlCenter
    end
    object lblhistory: TLabel
      Left = 255
      Top = 1
      Width = 4
      Height = 16
      HelpContext = 1218006
      Align = alTop
      Alignment = taRightJustify
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
    end
    object NumberEdit: TEdit
      AlignWithMargins = True
      Left = 4
      Top = 20
      Width = 252
      Height = 32
      HelpContext = 1218007
      Align = alTop
      Alignment = taRightJustify
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      Text = '0'
    end
  end
  object DNMPanel1: TDNMPanel [4]
    Left = 0
    Top = 82
    Width = 260
    Height = 260
    HelpContext = 1218008
    Align = alTop
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentColor = True
    ParentFont = False
    TabOrder = 1
    Transparent = False
    ExplicitLeft = 1
    ExplicitWidth = 265
    ExplicitHeight = 211
    object Addition: TDNMSpeedButton
      Left = 159
      Top = 55
      Width = 45
      Height = 45
      HelpContext = 1218009
      Caption = '+'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 0
      OnClick = AdditionClick
    end
    object Subtraction: TDNMSpeedButton
      Left = 159
      Top = 106
      Width = 45
      Height = 45
      HelpContext = 1218010
      Caption = '-'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 1
      OnClick = SubtractionClick
    end
    object Multiplication: TDNMSpeedButton
      Left = 159
      Top = 156
      Width = 45
      Height = 45
      HelpContext = 1218011
      Caption = 'X'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 2
      OnClick = MultiplicationClick
    end
    object Division: TDNMSpeedButton
      Left = 159
      Top = 207
      Width = 45
      Height = 45
      HelpContext = 1218012
      Caption = '/'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 3
      OnClick = DivisionClick
    end
    object One: TDNMSpeedButton
      Left = 6
      Top = 156
      Width = 45
      Height = 45
      HelpContext = 1218013
      Caption = '1'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 4
      OnClick = NumberButtonClick
    end
    object Two: TDNMSpeedButton
      Left = 57
      Top = 156
      Width = 45
      Height = 45
      HelpContext = 1218014
      Caption = '2'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 5
      OnClick = NumberButtonClick
    end
    object three: TDNMSpeedButton
      Left = 108
      Top = 156
      Width = 45
      Height = 45
      HelpContext = 1218015
      Caption = '3'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 6
      OnClick = NumberButtonClick
    end
    object Four: TDNMSpeedButton
      Left = 6
      Top = 106
      Width = 45
      Height = 45
      HelpContext = 1218016
      Caption = '4'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 7
      OnClick = NumberButtonClick
    end
    object five: TDNMSpeedButton
      Left = 57
      Top = 106
      Width = 45
      Height = 45
      HelpContext = 1218017
      Caption = '5'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 8
      OnClick = NumberButtonClick
    end
    object Six: TDNMSpeedButton
      Left = 108
      Top = 106
      Width = 45
      Height = 45
      HelpContext = 1218018
      Caption = '6'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 9
      OnClick = NumberButtonClick
    end
    object Seven: TDNMSpeedButton
      Left = 6
      Top = 55
      Width = 45
      Height = 45
      HelpContext = 1218019
      Caption = '7'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 10
      OnClick = NumberButtonClick
    end
    object Eight: TDNMSpeedButton
      Left = 57
      Top = 55
      Width = 45
      Height = 45
      HelpContext = 1218020
      Caption = '8'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 11
      OnClick = NumberButtonClick
    end
    object nine: TDNMSpeedButton
      Left = 108
      Top = 55
      Width = 45
      Height = 45
      HelpContext = 1218021
      Caption = '9'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 12
      OnClick = NumberButtonClick
    end
    object Zero: TDNMSpeedButton
      Left = 6
      Top = 207
      Width = 45
      Height = 45
      HelpContext = 1218022
      Caption = '0'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 13
      OnClick = NumberButtonClick
    end
    object Decimal: TDNMSpeedButton
      Left = 57
      Top = 207
      Width = 45
      Height = 45
      HelpContext = 1218023
      Caption = '.'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 14
      OnClick = DecimalClick
    end
    object Enter: TDNMSpeedButton
      Left = 210
      Top = 55
      Width = 45
      Height = 197
      HelpContext = 1218024
      Caption = '='
      Color = clWhite
      Default = True
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 15
      OnClick = EnterClick
    end
    object ClearValue: TDNMSpeedButton
      Left = 57
      Top = 5
      Width = 45
      Height = 45
      Hint = 'Clear the Current entry'
      HelpContext = 1218025
      Caption = 'CE'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      Style = bsModern
      TabOrder = 16
      OnClick = ClearValueClick
    end
    object Negative: TDNMSpeedButton
      Left = 108
      Top = 207
      Width = 45
      Height = 45
      HelpContext = 1218026
      Caption = #177
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 17
      WordWrap = True
      OnClick = NegativeClick
    end
    object Reset: TDNMSpeedButton
      Left = 108
      Top = 5
      Width = 45
      Height = 45
      Hint = 'Clear Current Calculation'
      HelpContext = 1218027
      Caption = 'C'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      Style = bsModern
      TabOrder = 18
      OnClick = ResetClick
    end
    object btnBack: TDNMSpeedButton
      Left = 6
      Top = 5
      Width = 45
      Height = 45
      HelpContext = 1218028
      Caption = #8592
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      Style = bsModern
      TabOrder = 19
      OnClick = btnBackClick
    end
    object openbracket: TDNMSpeedButton
      Left = 159
      Top = 5
      Width = 45
      Height = 45
      Hint = 'Clear Current Calculation'
      HelpContext = 1218029
      Caption = '('
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      Style = bsModern
      TabOrder = 20
      OnClick = openbracketClick
    end
    object closedBracket: TDNMSpeedButton
      Left = 210
      Top = 5
      Width = 45
      Height = 45
      HelpContext = 1218030
      Caption = ')'
      Color = clWhite
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'MS Sans Serif'
      HotTrackFont.Style = []
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      Style = bsModern
      TabOrder = 21
      OnClick = closedBracketClick
    end
  end
  object DNMPanel2: TDNMPanel [5]
    Left = 0
    Top = 342
    Width = 260
    Height = 65
    HelpContext = 1218031
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentColor = True
    ParentFont = False
    TabOrder = 2
    Transparent = False
    ExplicitTop = 327
    ExplicitHeight = 56
    DesignSize = (
      260
      65)
    object lblResult: TLabel
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 252
      Height = 24
      HelpContext = 1218032
      Align = alTop
      Alignment = taRightJustify
      Caption = 'Result := 0.0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMaroon
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      Layout = tlCenter
      Visible = False
      ExplicitLeft = 131
      ExplicitWidth = 125
    end
    object lblMsg: TLabel
      Left = 1
      Top = 36
      Width = 258
      Height = 28
      HelpContext = 1218033
      Align = alBottom
      Alignment = taCenter
      Caption = 
        'Hit ENTER Key to do the Calculation and ENTER again to close the' +
        ' calculator and return value'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMaroon
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      WordWrap = True
      ExplicitWidth = 257
    end
    object btnCancel: TDNMSpeedButton
      Left = 42
      Top = 6
      Width = 80
      Height = 28
      HelpContext = 1218034
      Anchors = [akTop]
      Cancel = True
      Caption = 'Cancel'
      Color = 9211135
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackColor = clBtnShadow
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -12
      HotTrackFont.Name = 'Arial'
      HotTrackFont.Style = [fsBold]
      Layout = blGlyphTop
      ModalResult = 2
      ParentColor = False
      ParentFont = False
      SlowDecease = True
      Style = bsModern
      TabOrder = 0
      OnClick = btnCancelClick
    end
    object btnOk: TDNMSpeedButton
      Left = 138
      Top = 6
      Width = 80
      Height = 28
      HelpContext = 1218035
      ParentCustomHint = False
      Anchors = [akTop]
      Caption = 'Ok'
      Color = 11075496
      DisableTransparent = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      HotTrackColor = 11075496
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -12
      HotTrackFont.Name = 'Arial'
      HotTrackFont.Style = [fsBold]
      Layout = blGlyphTop
      ModalResult = 1
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowHint = True
      Style = bsModern
      TabOrder = 1
      OnClick = btnOkClick
    end
  end
  inherited tmrProcessMessage: TTimer
    Left = 273
    Top = 339
  end
  inherited tmrdelay: TTimer
    Left = 160
    Top = 392
  end
  inherited popSpelling: TPopupMenu
    Left = 64
    Top = 392
  end
end
