object fmDraw: TfmDraw
  Left = 606
  Top = 257
  HelpContext = 1053001
  ClientHeight = 213
  ClientWidth = 312
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = True
  Position = poMainFormCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TDNMPanel
    Left = 0
    Top = 0
    Width = 312
    Height = 213
    HelpContext = 1053002
    Align = alTop
    Color = clWhite
    Constraints.MaxHeight = 250
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    Transparent = False
    object PaintBox1: TPaintBox
      AlignWithMargins = True
      Left = 7
      Top = 7
      Width = 298
      Height = 199
      HelpContext = 1053003
      Margins.Left = 6
      Margins.Top = 6
      Margins.Right = 6
      Margins.Bottom = 6
      Align = alClient
      Color = clWhite
      ParentColor = False
      OnMouseDown = PaintBox1MouseDown
      OnMouseMove = PaintBox1MouseMove
      OnMouseUp = PaintBox1MouseUp
      OnPaint = PaintBox1Paint
      ExplicitLeft = 14
      ExplicitTop = 0
    end
  end
end
