inherited fmMessageBase: TfmMessageBase
  Left = 54
  Top = 353
  HelpContext = 717000
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = 'fmMessageBase'
  ClientHeight = 195
  ClientWidth = 536
  Font.Charset = ANSI_CHARSET
  Font.Height = -12
  Font.Name = 'Arial'
  Font.Style = [fsBold]
  FormStyle = fsStayOnTop
  OldCreateOrder = True
  ExplicitLeft = 54
  ExplicitTop = 353
  ExplicitWidth = 552
  ExplicitHeight = 234
  PixelsPerInch = 96
  TextHeight = 15
  inherited lblSkingroupMsg: TLabel
    Top = 195
    Width = 536
    HelpContext = 717008
    ExplicitTop = 310
    ExplicitWidth = 517
  end
  object DnMPanel1: TDNMPanel [4]
    Left = 0
    Top = 0
    Width = 536
    Height = 195
    HelpContext = 717001
    Align = alClient
    BevelInner = bvRaised
    BorderWidth = 1
    BorderStyle = bsSingle
    Color = 16777175
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    object lbltop: TLabel
      AlignWithMargins = True
      Left = 6
      Top = 6
      Width = 520
      Height = 22
      HelpContext = 717004
      Align = alTop
      Alignment = taCenter
      Caption = 'Question'
      Color = clMoneyGreen
      Font.Charset = ANSI_CHARSET
      Font.Color = clGreen
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
      Layout = tlCenter
      WordWrap = True
      ExplicitWidth = 76
    end
    object lblBottom: TLabel
      AlignWithMargins = True
      Left = 6
      Top = 96
      Width = 520
      Height = 22
      HelpContext = 717010
      Align = alBottom
      Alignment = taCenter
      Caption = 'Question'
      Color = clMoneyGreen
      Font.Charset = ANSI_CHARSET
      Font.Color = clGreen
      Font.Height = -19
      Font.Name = 'Arial'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      Transparent = True
      Layout = tlCenter
      WordWrap = True
      ExplicitWidth = 76
    end
    object pnlFooter: TDNMPanel
      Left = 3
      Top = 121
      Width = 526
      Height = 50
      HelpContext = 717002
      Align = alBottom
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentColor = True
      ParentFont = False
      TabOrder = 0
      Transparent = False
    end
    object pnlDetails: TDNMPanel
      Left = 3
      Top = 31
      Width = 526
      Height = 62
      HelpContext = 717005
      Align = alClient
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentColor = True
      ParentFont = False
      TabOrder = 1
      Transparent = False
      object Bevel1: TBevel
        Left = 1
        Top = 1
        Width = 524
        Height = 1
        HelpContext = 717007
        Align = alTop
        Shape = bsTopLine
        ExplicitWidth = 480
      end
    end
    object chk: TCheckBox
      Left = 3
      Top = 171
      Width = 526
      Height = 17
      HelpContext = 717011
      Align = alBottom
      Caption = 'chk'
      TabOrder = 2
      Visible = False
      OnClick = chkClick
    end
  end
end
