object frProcessItem: TfrProcessItem
  Left = 0
  Top = 0
  Width = 586
  Height = 71
  AutoScroll = False
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Arial'
  Font.Style = []
  ParentColor = False
  ParentFont = False
  TabOrder = 0
  OnResize = FrameResize
  HelpContext = 599000
  object Bevel1: TBevel
    Left = 0
    Top = 69
    Width = 586
    Height = 2
    Align = alBottom
    Shape = bsBottomLine
    Style = bsRaised
    HelpContext = 599001
  end
  object Bevel2: TBevel
    Left = 0
    Top = 0
    Width = 586
    Height = 2
    Align = alTop
    Shape = bsTopLine
    Style = bsRaised
    HelpContext = 599002
  end
  object pnlMain: TPanel
    Left = 0
    Top = 2
    Width = 586
    Height = 67
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    OnClick = ControlClick
    HelpContext = 599003
    object pnlRef: TPanel
      Left = 0
      Top = 0
      Width = 73
      Height = 67
      Align = alLeft
      BevelOuter = bvNone
      Caption = '123'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = ControlClick
      HelpContext = 599004
    end
    object grdLines: TStringGrid
      Left = 104
      Top = 4
      Width = 273
      Height = 57
      Cursor = crArrow
      BorderStyle = bsNone
      DefaultColWidth = 150
      DefaultRowHeight = 19
      Enabled = False
      FixedCols = 0
      RowCount = 2
      FixedRows = 0
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Arial'
      Font.Style = []
      GridLineWidth = 0
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goDrawFocusSelected]
      ParentFont = False
      ScrollBars = ssNone
      TabOrder = 1
      OnClick = ControlClick
      HelpContext = 599005
    end
    object pnlRight: TPanel
      Left = 560
      Top = 0
      Width = 26
      Height = 67
      BevelOuter = bvNone
      TabOrder = 2
      OnClick = ControlClick
      HelpContext = 599006
    end
    object pnlButtons: TPanel
      Left = 416
      Top = 8
      Width = 121
      Height = 57
      BevelOuter = bvNone
      TabOrder = 3
      OnClick = ControlClick
      HelpContext = 599007
      object btnNext: TPanel
        Left = 64
        Top = 0
        Width = 57
        Height = 57
        BevelInner = bvRaised
        BevelOuter = bvNone
        Caption = '>>'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        OnClick = btnNextClick
        OnMouseDown = btnPriorMouseDown
        OnMouseUp = btnPriorMouseUp
        HelpContext = 599008
      end
      object btnPrior: TPanel
        Left = 0
        Top = 0
        Width = 57
        Height = 57
        BevelInner = bvRaised
        BevelOuter = bvNone
        Caption = '<<'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
        OnClick = btnPriorClick
        OnMouseDown = btnPriorMouseDown
        OnMouseUp = btnPriorMouseUp
        HelpContext = 599009
      end
    end
  end
end
