inherited DashBoardTopTenBaseGUI: TDashBoardTopTenBaseGUI
  Left = 398
  Top = 303
  HelpContext = 676000
  Caption = 'BASE'
  ClientHeight = 339
  ClientWidth = 329
  ExplicitLeft = 398
  ExplicitTop = 303
  ExplicitWidth = 345
  ExplicitHeight = 378
  PixelsPerInch = 96
  TextHeight = 13
  inherited lblSkingroupMsg: TLabel
    Top = 339
    Width = 329
    HelpContext = 676054
    ExplicitTop = 339
    ExplicitWidth = 329
  end
  inherited pnlmain: TDNMPanel
    Width = 329
    Height = 339
    HelpContext = 676001
    ExplicitWidth = 329
    ExplicitHeight = 339
    inherited pnlHeader: TDNMPanel
      Width = 327
      Height = 29
      HelpContext = 676002
      BevelOuter = bvNone
      Caption = 'Top Ten'
      ExplicitWidth = 327
      ExplicitHeight = 29
    end
    inherited pnlDetails: TDNMPanel
      Top = 63
      Width = 327
      Height = 275
      HelpContext = 676003
      ExplicitTop = 63
      ExplicitWidth = 327
      ExplicitHeight = 275
      object pnlGraph: TDNMPanel
        Left = 1
        Top = 1
        Width = 325
        Height = 273
        HelpContext = 676004
        Align = alClient
        BevelOuter = bvNone
        Color = clInfoBk
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
        Transparent = False
      end
      object pnldata: TDNMPanel
        Left = 1
        Top = 1
        Width = 325
        Height = 273
        HelpContext = 676005
        Align = alClient
        BevelOuter = bvNone
        Color = clInfoBk
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        Transparent = False
        DesignSize = (
          325
          273)
        object lblProductname: TLabel
          Left = 10
          Top = 8
          Width = 83
          Height = 15
          HelpContext = 676006
          Anchors = [akLeft]
          Caption = 'Product name '
        end
        object Label3: TLabel
          Left = 167
          Top = 7
          Width = 69
          Height = 15
          HelpContext = 676007
          Alignment = taRightJustify
          Anchors = [akLeft]
          AutoSize = False
          Caption = 'Quantity'
        end
        object Label5: TLabel
          Left = 238
          Top = 8
          Width = 80
          Height = 15
          HelpContext = 676008
          Alignment = taRightJustify
          Anchors = [akLeft]
          AutoSize = False
          Caption = 'Price'
        end
        object Label4: TLabel
          Left = 340
          Top = 7
          Width = 80
          Height = 15
          HelpContext = 676009
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
        end
        object Bevel1: TBevel
          Left = 0
          Top = 28
          Width = 328
          Height = 5
          HelpContext = 676010
          Anchors = [akLeft, akRight]
          Shape = bsTopLine
        end
        object pr1: TLabel
          Left = 9
          Top = 35
          Width = 36
          Height = 15
          HelpContext = 676011
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q1: TLabel
          Left = 156
          Top = 35
          Width = 80
          Height = 15
          HelpContext = 676012
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p1: TLabel
          Left = 238
          Top = 35
          Width = 80
          Height = 15
          HelpContext = 676013
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m1: TLabel
          Left = 339
          Top = 35
          Width = 80
          Height = 15
          HelpContext = 676014
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr2: TLabel
          Left = 9
          Top = 58
          Width = 36
          Height = 15
          HelpContext = 676015
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q2: TLabel
          Left = 156
          Top = 58
          Width = 80
          Height = 15
          HelpContext = 676016
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p2: TLabel
          Left = 238
          Top = 58
          Width = 80
          Height = 15
          HelpContext = 676017
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m2: TLabel
          Left = 339
          Top = 58
          Width = 80
          Height = 15
          HelpContext = 676018
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr4: TLabel
          Left = 9
          Top = 106
          Width = 36
          Height = 15
          HelpContext = 676019
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q4: TLabel
          Left = 156
          Top = 106
          Width = 80
          Height = 15
          HelpContext = 676020
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p4: TLabel
          Left = 238
          Top = 106
          Width = 80
          Height = 15
          HelpContext = 676021
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m4: TLabel
          Left = 339
          Top = 106
          Width = 80
          Height = 15
          HelpContext = 676022
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr3: TLabel
          Left = 9
          Top = 82
          Width = 36
          Height = 15
          HelpContext = 676023
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q3: TLabel
          Left = 156
          Top = 82
          Width = 80
          Height = 15
          HelpContext = 676024
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p3: TLabel
          Left = 238
          Top = 82
          Width = 80
          Height = 15
          HelpContext = 676025
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m3: TLabel
          Left = 339
          Top = 82
          Width = 80
          Height = 15
          HelpContext = 676026
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr8: TLabel
          Left = 9
          Top = 202
          Width = 36
          Height = 15
          HelpContext = 676027
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q8: TLabel
          Left = 156
          Top = 202
          Width = 80
          Height = 15
          HelpContext = 676028
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p8: TLabel
          Left = 238
          Top = 202
          Width = 80
          Height = 15
          HelpContext = 676029
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m8: TLabel
          Left = 339
          Top = 202
          Width = 80
          Height = 15
          HelpContext = 676030
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr7: TLabel
          Left = 9
          Top = 178
          Width = 36
          Height = 15
          HelpContext = 676031
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q7: TLabel
          Left = 156
          Top = 178
          Width = 80
          Height = 15
          HelpContext = 676032
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p7: TLabel
          Left = 238
          Top = 178
          Width = 80
          Height = 15
          HelpContext = 676033
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m7: TLabel
          Left = 339
          Top = 178
          Width = 80
          Height = 15
          HelpContext = 676034
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr6: TLabel
          Left = 9
          Top = 154
          Width = 36
          Height = 15
          HelpContext = 676035
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr5: TLabel
          Left = 9
          Top = 130
          Width = 36
          Height = 15
          HelpContext = 676036
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q5: TLabel
          Left = 156
          Top = 130
          Width = 80
          Height = 15
          HelpContext = 676037
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q6: TLabel
          Left = 156
          Top = 154
          Width = 80
          Height = 15
          HelpContext = 676038
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p6: TLabel
          Left = 238
          Top = 154
          Width = 80
          Height = 15
          HelpContext = 676039
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p5: TLabel
          Left = 238
          Top = 130
          Width = 80
          Height = 15
          HelpContext = 676040
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m5: TLabel
          Left = 339
          Top = 130
          Width = 80
          Height = 15
          HelpContext = 676041
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m6: TLabel
          Left = 339
          Top = 154
          Width = 80
          Height = 15
          HelpContext = 676042
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr9: TLabel
          Left = 9
          Top = 226
          Width = 36
          Height = 15
          HelpContext = 676043
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object pr10: TLabel
          Left = 9
          Top = 250
          Width = 36
          Height = 15
          HelpContext = 676044
          Anchors = [akLeft]
          Caption = 'Name '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q10: TLabel
          Left = 156
          Top = 250
          Width = 80
          Height = 15
          HelpContext = 676045
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object q9: TLabel
          Left = 156
          Top = 226
          Width = 80
          Height = 15
          HelpContext = 676046
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p10: TLabel
          Left = 238
          Top = 250
          Width = 80
          Height = 15
          HelpContext = 676047
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object p9: TLabel
          Left = 238
          Top = 226
          Width = 80
          Height = 15
          HelpContext = 676048
          Alignment = taRightJustify
          Anchors = [akRight]
          AutoSize = False
          Caption = 'Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m10: TLabel
          Left = 339
          Top = 250
          Width = 80
          Height = 15
          HelpContext = 676049
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object m9: TLabel
          Left = 339
          Top = 226
          Width = 80
          Height = 15
          HelpContext = 676050
          Alignment = taRightJustify
          AutoSize = False
          Caption = 'Margin'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clNavy
          Font.Height = -12
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Bevel2: TBevel
          Left = 156
          Top = 28
          Width = 1
          Height = 246
          HelpContext = 676051
          Anchors = [akRight]
          Shape = bsLeftLine
        end
        object Bevel3: TBevel
          Left = 238
          Top = 28
          Width = 1
          Height = 246
          HelpContext = 676052
          Anchors = [akRight]
          Shape = bsLeftLine
        end
      end
    end
    object pnltop: TDNMPanel
      Left = 1
      Top = 30
      Width = 327
      Height = 33
      HelpContext = 676053
      Align = alTop
      BevelOuter = bvNone
      Color = clInfoBk
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      Transparent = False
      object grpView: TwwRadioGroup
        Left = 214
        Top = 0
        Width = 113
        Height = 33
        HelpContext = 676055
        DisableThemes = False
        ItemIndex = 1
        Align = alRight
        Caption = 'Mode'
        Columns = 2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        Items.Strings = (
          'Graph'
          'Value')
        ParentFont = False
        TabOrder = 1
        OnClick = grpViewClick
      end
      object grpFilters: TwwRadioGroup
        Left = 0
        Top = 0
        Width = 214
        Height = 33
        HelpContext = 676056
        Align = alClient
        Caption = 'Top Ten By'
        Columns = 3
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ItemIndex = 0
        Items.Strings = (
          'Price'
          'Margin'
          'Quantity')
        ParentFont = False
        TabOrder = 0
        OnClick = grpFiltersClick
      end
    end
  end
  inherited Customisemenu: TPopupMenu
    HelpContext = 676054
    Top = 104
  end
  object Qrymain: TERPQuery
    Connection = MyConnection
    AfterOpen = QrymainAfterOpen
    Left = 139
    Top = 186
  end
  object MyConnection: TERPConnection
    Port = 3309
    Options.UseUnicode = True
    Options.KeepDesignConnected = False
    PoolingOptions.MinPoolSize = 1
    PoolingOptions.ConnectionLifetime = 180
    Pooling = True
    LoginPrompt = False
    Left = 89
    Top = 209
  end
end
