inherited DashBoardAnLGUI: TDashBoardAnLGUI
  Left = 333
  Top = 160
  HelpContext = 678000
  Caption = 'DashBoardAnLGUI'
  ClientHeight = 279
  ClientWidth = 364
  ExplicitLeft = 333
  ExplicitTop = 160
  ExplicitWidth = 380
  ExplicitHeight = 318
  PixelsPerInch = 96
  TextHeight = 13
  inherited lblSkingroupMsg: TLabel
    Top = 279
    Width = 364
    ExplicitTop = 279
    ExplicitWidth = 364
    HelpContext = 678086
  end
  inherited pnlmain: TDNMPanel
    Width = 364
    Height = 279
    HelpContext = 678001
    OnResize = pnlmainResize
    ExplicitWidth = 364
    ExplicitHeight = 279
    inherited pnlHeader: TDNMPanel
      Top = 24
      Width = 362
      Height = 27
      HelpContext = 678002
      Caption = ''
      OnResize = pnlHeaderResize
      ExplicitTop = 24
      ExplicitWidth = 362
      ExplicitHeight = 27
      DesignSize = (
        362
        27)
      object btnasset: TDNMSpeedButton
        Left = 30
        Top = 2
        Width = 77
        Height = 23
        HelpContext = 678003
        Anchors = []
        Caption = 'Asset'
        DisableTransparent = False
        HotTrackColor = clBtnShadow
        HotTrackFont.Charset = DEFAULT_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -11
        HotTrackFont.Name = 'MS Sans Serif'
        HotTrackFont.Style = []
        SlowDecease = True
        Style = bsModern
        TabOrder = 0
        AutoDisableParentOnclick = True
        OnClick = tabclick
      end
      object btnliab: TDNMSpeedButton
        Left = 143
        Top = 2
        Width = 77
        Height = 23
        HelpContext = 678004
        Anchors = []
        Caption = 'Liability'
        DisableTransparent = False
        HotTrackColor = clBtnShadow
        HotTrackFont.Charset = DEFAULT_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -11
        HotTrackFont.Name = 'MS Sans Serif'
        HotTrackFont.Style = []
        Style = bsModern
        TabOrder = 1
        AutoDisableParentOnclick = True
        OnClick = tabclick
      end
      object btnnet: TDNMSpeedButton
        Left = 254
        Top = 2
        Width = 78
        Height = 23
        HelpContext = 678005
        Anchors = []
        Caption = 'Summary'
        Color = clMedGray
        DisableTransparent = False
        HotTrackColor = clBtnShadow
        HotTrackFont.Charset = DEFAULT_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -11
        HotTrackFont.Name = 'MS Sans Serif'
        HotTrackFont.Style = []
        ParentColor = False
        Style = bsModern
        TabOrder = 2
        AutoDisableParentOnclick = True
        OnClick = tabclick
      end
    end
    inherited pnlDetails: TDNMPanel
      Top = 51
      Width = 362
      Height = 227
      HelpContext = 678006
      Font.Color = clNavy
      ExplicitTop = 51
      ExplicitWidth = 362
      ExplicitHeight = 227
      object PageControl: TPageControl
        Left = 1
        Top = 1
        Width = 360
        Height = 225
        HelpContext = 678007
        ActivePage = TabSheet2
        Align = alClient
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clNavy
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        TabWidth = 119
        Visible = False
        OnChange = PageControlChange
        object pgAsset: TTabSheet
          HelpContext = 678008
          Caption = 'Assets'
          object pnlAsset: TDNMPanel
            Left = 0
            Top = 0
            Width = 352
            Height = 195
            HelpContext = 678009
            Align = alClient
            Color = clInfoBk
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -12
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
            Transparent = False
            DesignSize = (
              352
              195)
            object Asset2: TBevel
              Left = 3
              Top = 18
              Width = 344
              Height = 173
              HelpContext = 678010
              Anchors = [akLeft, akTop, akRight, akBottom]
            end
            object Asset1: TBevel
              Left = 1
              Top = 20
              Width = 347
              Height = 171
              HelpContext = 678011
              Anchors = [akLeft, akTop, akRight, akBottom]
              Style = bsRaised
            end
            object des1: TLabel
              Left = 15
              Top = 20
              Width = 31
              Height = 15
              HelpContext = 678012
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object des2: TLabel
              Left = 15
              Top = 45
              Width = 31
              Height = 15
              HelpContext = 678013
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex5: TLabel
              Left = 286
              Top = 118
              Width = 34
              Height = 15
              HelpContext = 678014
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex2: TLabel
              Left = 298
              Top = 45
              Width = 23
              Height = 15
              HelpContext = 678015
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex1: TLabel
              Left = 298
              Top = 20
              Width = 23
              Height = 15
              HelpContext = 678016
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object baGross: TLabel
              Left = 286
              Top = 146
              Width = 34
              Height = 15
              HelpContext = 678017
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object vaGross: TLabel
              Left = 286
              Top = 173
              Width = 34
              Height = 15
              HelpContext = 678018
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object des3: TLabel
              Left = 15
              Top = 68
              Width = 31
              Height = 15
              HelpContext = 678019
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex3: TLabel
              Left = 298
              Top = 68
              Width = 23
              Height = 15
              HelpContext = 678020
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object des4: TLabel
              Left = 15
              Top = 91
              Width = 31
              Height = 15
              HelpContext = 678021
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex4: TLabel
              Left = 298
              Top = 91
              Width = 23
              Height = 15
              HelpContext = 678022
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object lblTotal: TLabel
              Left = 295
              Top = 0
              Width = 26
              Height = 14
              HelpContext = 678023
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlack
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object Label1: TLabel
              Left = 39
              Top = 173
              Width = 50
              Height = 15
              HelpContext = 678024
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Variance'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object Label2: TLabel
              Left = 48
              Top = 146
              Width = 40
              Height = 15
              HelpContext = 678025
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Budget'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object des5: TLabel
              Left = 60
              Top = 118
              Width = 27
              Height = 15
              HelpContext = 678026
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clNavy
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object Bevel1: TBevel
              Left = 4
              Top = 109
              Width = 345
              Height = 2
              HelpContext = 678027
              Anchors = [akLeft, akRight]
              Shape = bsTopLine
            end
          end
        end
        object TabSheet1: TTabSheet
          HelpContext = 678028
          Caption = 'Liabilities'
          ImageIndex = 1
          ExplicitLeft = 0
          ExplicitTop = 0
          ExplicitWidth = 0
          ExplicitHeight = 0
          object pnlLiab: TDNMPanel
            Left = 0
            Top = 0
            Width = 352
            Height = 195
            HelpContext = 678029
            Align = alClient
            Color = clInfoBk
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -12
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
            Transparent = False
            DesignSize = (
              352
              195)
            object Liab1: TBevel
              Left = -1
              Top = 13
              Width = 960
              Height = 613
              HelpContext = 678030
              Anchors = [akLeft, akTop, akRight, akBottom]
              Style = bsRaised
            end
            object Liab2: TBevel
              Left = 1
              Top = 16
              Width = 958
              Height = 612
              HelpContext = 678031
              Anchors = [akLeft, akTop, akRight, akBottom]
            end
            object Bevel5: TBevel
              Left = 2
              Top = 318
              Width = 961
              Height = 1
              HelpContext = 678032
              Anchors = [akLeft, akRight]
              Shape = bsTopLine
            end
            object des6: TLabel
              Left = 16
              Top = 69
              Width = 41
              Height = 15
              HelpContext = 678033
              Anchors = []
              Caption = 'Liability'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex9: TLabel
              Left = 292
              Top = 354
              Width = 34
              Height = 15
              HelpContext = 678034
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex6: TLabel
              Left = 303
              Top = 69
              Width = 23
              Height = 15
              HelpContext = 678035
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object bgross: TLabel
              Left = 292
              Top = 441
              Width = 34
              Height = 15
              HelpContext = 678036
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object vgross: TLabel
              Left = 292
              Top = 516
              Width = 34
              Height = 15
              HelpContext = 678037
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Gross'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object des8: TLabel
              Left = 15
              Top = 207
              Width = 31
              Height = 15
              HelpContext = 678038
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex8: TLabel
              Left = 303
              Top = 207
              Width = 23
              Height = 15
              HelpContext = 678039
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object des7: TLabel
              Left = 15
              Top = 138
              Width = 31
              Height = 15
              HelpContext = 678040
              Anchors = []
              Caption = 'Asset'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object ex7: TLabel
              Left = 303
              Top = 138
              Width = 23
              Height = 15
              HelpContext = 678041
              Alignment = taRightJustify
              Anchors = []
              Caption = 'total'
              Color = clBtnFace
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = []
              ParentColor = False
              ParentFont = False
              Transparent = True
            end
            object Label17: TLabel
              Left = 300
              Top = 21
              Width = 26
              Height = 14
              HelpContext = 678042
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clBlack
              Font.Height = -11
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object des9: TLabel
              Left = 60
              Top = 354
              Width = 27
              Height = 15
              HelpContext = 678043
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Total'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object Label19: TLabel
              Left = 47
              Top = 441
              Width = 40
              Height = 15
              HelpContext = 678044
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Budget'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
            object Label20: TLabel
              Left = 36
              Top = 516
              Width = 50
              Height = 15
              HelpContext = 678045
              Alignment = taRightJustify
              Anchors = []
              Caption = 'Variance'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clMaroon
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              Transparent = True
            end
          end
        end
        object TabSheet2: TTabSheet
          HelpContext = 678046
          Caption = 'Net'
          ImageIndex = 2
          object pnlnet: TDNMPanel
            Left = 0
            Top = 0
            Width = 352
            Height = 195
            HelpContext = 678047
            Align = alClient
            Color = clInfoBk
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clNavy
            Font.Height = -12
            Font.Name = 'Arial'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
            OnResize = pnlnetResize
            DesignSize = (
              352
              195)
            object Bevel7: TBevel
              Left = 3
              Top = 68
              Width = 986
              Height = 1
              HelpContext = 678048
              Anchors = [akLeft, akRight]
              Shape = bsTopLine
            end
            object pnlliabsummary: TDNMPanel
              Left = 1
              Top = 65
              Width = 350
              Height = 64
              HelpContext = 678049
              Align = alTop
              Color = clYellow
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              TabOrder = 0
              Transparent = False
              DesignSize = (
                350
                64)
              object Bevel4: TBevel
                Left = 118
                Top = -128
                Width = 12
                Height = 192
                HelpContext = 678050
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
              object Bevel2: TBevel
                Left = 235
                Top = -128
                Width = 11
                Height = 192
                HelpContext = 678051
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
              object Label4: TLabel
                Left = 13
                Top = 1
                Width = 54
                Height = 15
                HelpContext = 678052
                Alignment = taRightJustify
                Anchors = []
                Caption = 'Liabilities'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clMaroon
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold, fsUnderline]
                ParentFont = False
                Transparent = True
              end
              object Label5: TLabel
                Left = 75
                Top = 16
                Width = 36
                Height = 15
                HelpContext = 678053
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Actual'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object ex9c: TLabel
                Left = 92
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678054
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clMaroon
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object Label6: TLabel
                Left = 186
                Top = 16
                Width = 40
                Height = 15
                HelpContext = 678055
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Budget'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object bgrossc: TLabel
                Left = 209
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678056
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clMaroon
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object Label7: TLabel
                Left = 289
                Top = 16
                Width = 50
                Height = 15
                HelpContext = 678057
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Variance'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object vGrossc: TLabel
                Left = 322
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678058
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clMaroon
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object vgross1: TLabel
                Left = 312
                Top = 48
                Width = 29
                Height = 7
                HelpContext = 678059
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clNavy
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
              object vgross2: TLabel
                Left = 312
                Top = 53
                Width = 29
                Height = 8
                HelpContext = 678060
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clBlue
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
            end
            object pnlAssetsummary: TDNMPanel
              Left = 1
              Top = 1
              Width = 350
              Height = 64
              HelpContext = 678061
              Align = alTop
              Color = clMoneyGreen
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              TabOrder = 1
              Transparent = False
              DesignSize = (
                350
                64)
              object Label12: TLabel
                Left = 4
                Top = 3
                Width = 33
                Height = 15
                HelpContext = 678062
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Asset'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold, fsUnderline]
                ParentFont = False
                Transparent = True
              end
              object Label13: TLabel
                Left = 75
                Top = 17
                Width = 36
                Height = 15
                HelpContext = 678063
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Actual'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object ex5c: TLabel
                Left = 92
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678064
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object Label15: TLabel
                Left = 188
                Top = 17
                Width = 40
                Height = 15
                HelpContext = 678065
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Budget'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object bagrossc: TLabel
                Left = 209
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678066
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object Label18: TLabel
                Left = 291
                Top = 17
                Width = 50
                Height = 15
                HelpContext = 678067
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Variance'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object vagrossc: TLabel
                Left = 322
                Top = 34
                Width = 19
                Height = 15
                HelpContext = 678068
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = []
                ParentFont = False
                Transparent = True
              end
              object vagross1: TLabel
                Left = 312
                Top = 48
                Width = 29
                Height = 7
                HelpContext = 678069
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clNavy
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
              object vagross2: TLabel
                Left = 312
                Top = 54
                Width = 29
                Height = 7
                HelpContext = 678070
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clBlue
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlue
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
              object Bevel9: TBevel
                Left = 118
                Top = -128
                Width = 12
                Height = 192
                HelpContext = 678071
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
              object Bevel10: TBevel
                Left = 235
                Top = -128
                Width = 11
                Height = 192
                HelpContext = 678072
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
            end
            object DNMPanel4: TDNMPanel
              Left = 1
              Top = 129
              Width = 350
              Height = 64
              HelpContext = 678073
              Align = alTop
              Color = clInfoBk
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -12
              Font.Name = 'Arial'
              Font.Style = [fsBold]
              ParentFont = False
              TabOrder = 2
              Transparent = False
              DesignSize = (
                350
                64)
              object Label3: TLabel
                Left = 8
                Top = 1
                Width = 19
                Height = 15
                HelpContext = 678074
                Anchors = []
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clGreen
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold, fsUnderline]
                ParentFont = False
                Transparent = True
              end
              object Label8: TLabel
                Left = 75
                Top = 9
                Width = 36
                Height = 15
                HelpContext = 678075
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Actual'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object ex10: TLabel
                Left = 93
                Top = 24
                Width = 19
                Height = 15
                HelpContext = 678076
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clGreen
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object Label9: TLabel
                Left = 186
                Top = 9
                Width = 40
                Height = 15
                HelpContext = 678077
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Budget'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object bnet: TLabel
                Left = 210
                Top = 24
                Width = 19
                Height = 15
                HelpContext = 678078
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clGreen
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object Label11: TLabel
                Left = 289
                Top = 9
                Width = 50
                Height = 15
                HelpContext = 678079
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Variance'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlack
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object vnet: TLabel
                Left = 323
                Top = 24
                Width = 19
                Height = 15
                HelpContext = 678080
                Alignment = taRightJustify
                Anchors = [akLeft]
                Caption = 'Net'
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clGreen
                Font.Height = -12
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentFont = False
                Transparent = True
              end
              object vnet1: TLabel
                Left = 312
                Top = 44
                Width = 30
                Height = 7
                HelpContext = 678081
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clNavy
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clNavy
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
              object vnet2: TLabel
                Left = 312
                Top = 50
                Width = 30
                Height = 7
                HelpContext = 678082
                Anchors = [akLeft]
                AutoSize = False
                Caption = 'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII'
                Color = clBlue
                Font.Charset = DEFAULT_CHARSET
                Font.Color = clBlue
                Font.Height = -7
                Font.Name = 'Arial'
                Font.Style = [fsBold]
                ParentColor = False
                ParentFont = False
              end
              object Bevel3: TBevel
                Left = 118
                Top = -124
                Width = 12
                Height = 193
                HelpContext = 678083
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
              object Bevel6: TBevel
                Left = 235
                Top = -124
                Width = 11
                Height = 193
                HelpContext = 678084
                Anchors = [akLeft]
                Shape = bsLeftLine
              end
            end
          end
        end
      end
    end
    object pnlsubheading: TDNMPanel
      Left = 1
      Top = 1
      Width = 362
      Height = 23
      HelpContext = 678085
      Align = alTop
      Caption = 'Asset and Liability Summary'
      Color = clInfoBk
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      Transparent = False
    end
  end
  inherited Customisemenu: TPopupMenu
    HelpContext = 678086
    Left = 248
    Top = 104
  end
end
