object fmHttp: TfmHttp
  Left = 870
  Top = 343
  HelpContext = 1645002
  Caption = 'fmHttp'
  ClientHeight = 548
  ClientWidth = 707
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 13
  object btnHttp1: TDNMSpeedButton
    Left = 21
    Top = 118
    Width = 86
    Height = 20
    HelpContext = 1645003
    Caption = 'Http Request'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 0
    AutoDisableParentOnclick = True
    OnClick = btnHttp1Click
  end
  object DNMSpeedButton1: TDNMSpeedButton
    Left = 159
    Top = 190
    Width = 87
    Height = 20
    HelpContext = 1645004
    Caption = 'DNMSpeedButton1'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 1
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton1Click
  end
  object Memo1: TMemo
    Left = 291
    Top = 102
    Width = 417
    Height = 315
    HelpContext = 1645005
    Lines.Strings = (
      'Memo1')
    TabOrder = 2
  end
  object DNMSpeedButton2: TDNMSpeedButton
    Left = 159
    Top = 215
    Width = 87
    Height = 20
    HelpContext = 1645006
    Caption = 'DNMSpeedButton2'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 3
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton2Click
  end
  object DNMSpeedButton3: TDNMSpeedButton
    Left = 159
    Top = 240
    Width = 87
    Height = 20
    HelpContext = 1645007
    Caption = 'DNMSpeedButton3'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 4
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton3Click
  end
  object DNMSpeedButton4: TDNMSpeedButton
    Left = 159
    Top = 265
    Width = 87
    Height = 20
    HelpContext = 1645008
    Caption = 'DNMSpeedButton4'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 5
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton4Click
  end
  object btnHttp2: TDNMSpeedButton
    Left = 113
    Top = 118
    Width = 86
    Height = 20
    HelpContext = 1645009
    Caption = 'Http Request'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 6
    AutoDisableParentOnclick = True
    OnClick = btnHttp1Click
  end
  object btnHttp3: TDNMSpeedButton
    Left = 199
    Top = 118
    Width = 87
    Height = 20
    HelpContext = 1645010
    Caption = 'Http Request'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 7
    AutoDisableParentOnclick = True
    OnClick = btnHttp1Click
  end
  object btnHttp4: TDNMSpeedButton
    Left = 159
    Top = 143
    Width = 87
    Height = 20
    HelpContext = 1645011
    Caption = 'Http Request'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 8
    AutoDisableParentOnclick = True
    OnClick = btnHttp1Click
  end
  object DNMSpeedButton5: TDNMSpeedButton
    Left = 159
    Top = 301
    Width = 87
    Height = 20
    HelpContext = 1645012
    Caption = 'WC1'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 9
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton5Click
  end
  object DNMSpeedButton6: TDNMSpeedButton
    Left = 159
    Top = 326
    Width = 87
    Height = 20
    HelpContext = 1645013
    Caption = 'WC2'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 10
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton6Click
  end
  object DNMSpeedButton7: TDNMSpeedButton
    Left = 159
    Top = 351
    Width = 87
    Height = 20
    HelpContext = 1645014
    Caption = 'WC3'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 11
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton7Click
  end
  object DNMSpeedButton8: TDNMSpeedButton
    Left = 159
    Top = 376
    Width = 87
    Height = 20
    HelpContext = 1645015
    Caption = 'WC4'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 12
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton8Click
  end
  object DNMSpeedButton9: TDNMSpeedButton
    Left = 28
    Top = 279
    Width = 86
    Height = 20
    HelpContext = 1645016
    Caption = 'WC'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 13
    AutoDisableParentOnclick = True
  end
  object DNMSpeedButton10: TDNMSpeedButton
    Left = 159
    Top = 401
    Width = 87
    Height = 20
    HelpContext = 1645017
    Caption = 'WC 5'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 14
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton10Click
  end
  object DNMSpeedButton11: TDNMSpeedButton
    Left = 159
    Top = 426
    Width = 87
    Height = 20
    HelpContext = 1645018
    Caption = 'WC 6'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 15
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton11Click
  end
  object DNMSpeedButton12: TDNMSpeedButton
    Left = 251
    Top = 426
    Width = 87
    Height = 20
    HelpContext = 1645019
    Caption = 'WC7'
    DisableTransparent = False
    HotTrackFont.Charset = ANSI_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -12
    HotTrackFont.Name = 'Arial'
    HotTrackFont.Style = [fsBold]
    TabOrder = 16
    AutoDisableParentOnclick = True
    OnClick = DNMSpeedButton12Click
  end
end
