unit frmrestcontact;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, BaseInputForm, StdCtrls, DB, MemDS, DBAccess, MyAccess,
  ERPdbComponents, ImgList, Menus, AdvMenus, DataState, SelectionDialog,
  AppEvnts, ExtCtrls, BusObjContact, BusObjBase;

type
  Tfmrestcontact = class(TBaseInputGUI)
    qryContacts: TERPQuery;
    qryContactsGlobalRef: TWideStringField;
    qryContactsContactID: TIntegerField;
    qryContactsCusID: TIntegerField;
    qryContactsSupID: TIntegerField;
    qryContactsEmployeeID: TIntegerField;
    qryContactsCompany: TWideStringField;
    qryContactsContactTitle: TWideStringField;
    qryContactsContactFirstName: TWideStringField;
    qryContactsContactSurName: TWideStringField;
    qryContactsContactAddress: TWideStringField;
    qryContactsContactAddress2: TWideStringField;
    qryContactsContactAddress3: TWideStringField;
    qryContactsContactCity: TWideStringField;
    qryContactsContactState: TWideStringField;
    qryContactsContactPcode: TWideStringField;
    qryContactsContactCountry: TWideStringField;
    qryContactsContactPH: TWideStringField;
    qryContactsContactAltPH: TWideStringField;
    qryContactsContactMOB: TWideStringField;
    qryContactsContactFax: TWideStringField;
    qryContactsContactEmail: TWideStringField;
    qryContactsNotes: TWideStringField;
    qryContactsEditedFlag: TWideStringField;
    qryContactsActive: TWideStringField;
    qryContactsCardNumber: TWideStringField;
    qryContactsAccountNo: TWideStringField;
    qryContactsJobTitle: TWideStringField;
    qryContactsContactIsCustomer: TWideStringField;
    qryContactsContactIsJob: TWideStringField;
    qryContactsContactIsSupplier: TWideStringField;
    qryContactsContactIsOtherContact: TWideStringField;
    qryContactsUseOnRun: TWideStringField;
    qryContactsmsTimeStamp: TDateTimeField;
    qryContactsLogMeInComputerIPAddress: TWideStringField;
    qryContactsLogMeInEmailPassword: TWideStringField;
    qryContactsLogMeInUserName: TWideStringField;
    qryContactsLogMeInPassword: TWideStringField;
    qryContactsLogMeInERPUserName: TWideStringField;
    qryContactsLogMeInERPPassword: TWideStringField;
    qryContactsLogMeIncomputerPassword: TWideStringField;
    qryContactsIsPrimarycontact: TWideStringField;
    qryContactsTeamviewerID: TWideStringField;
    frmContactSrc: TDataSource;
    qryContactscopy: TERPQuery;
    WideStringField1: TWideStringField;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    WideStringField2: TWideStringField;
    WideStringField3: TWideStringField;
    WideStringField4: TWideStringField;
    WideStringField5: TWideStringField;
    WideStringField6: TWideStringField;
    WideStringField7: TWideStringField;
    WideStringField8: TWideStringField;
    WideStringField9: TWideStringField;
    WideStringField10: TWideStringField;
    WideStringField11: TWideStringField;
    WideStringField12: TWideStringField;
    WideStringField13: TWideStringField;
    WideStringField14: TWideStringField;
    WideStringField15: TWideStringField;
    WideStringField16: TWideStringField;
    WideStringField17: TWideStringField;
    WideStringField18: TWideStringField;
    WideStringField19: TWideStringField;
    WideStringField20: TWideStringField;
    WideStringField21: TWideStringField;
    WideStringField22: TWideStringField;
    WideStringField23: TWideStringField;
    WideStringField24: TWideStringField;
    WideStringField25: TWideStringField;
    WideStringField26: TWideStringField;
    WideStringField27: TWideStringField;
    WideStringField28: TWideStringField;
    DateTimeField1: TDateTimeField;
    WideStringField29: TWideStringField;
    WideStringField30: TWideStringField;
    WideStringField31: TWideStringField;
    WideStringField32: TWideStringField;
    WideStringField33: TWideStringField;
    WideStringField34: TWideStringField;
    WideStringField35: TWideStringField;
    WideStringField36: TWideStringField;
    WideStringField37: TWideStringField;
    frmContactSrccopy: TDataSource;
    Button1: TButton;
    qryContactsdup: TERPQuery;
    WideStringField38: TWideStringField;
    IntegerField5: TIntegerField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    IntegerField8: TIntegerField;
    WideStringField39: TWideStringField;
    WideStringField40: TWideStringField;
    WideStringField41: TWideStringField;
    WideStringField42: TWideStringField;
    WideStringField43: TWideStringField;
    WideStringField44: TWideStringField;
    WideStringField45: TWideStringField;
    WideStringField46: TWideStringField;
    WideStringField47: TWideStringField;
    WideStringField48: TWideStringField;
    WideStringField49: TWideStringField;
    WideStringField50: TWideStringField;
    WideStringField51: TWideStringField;
    WideStringField52: TWideStringField;
    WideStringField53: TWideStringField;
    WideStringField54: TWideStringField;
    WideStringField55: TWideStringField;
    WideStringField56: TWideStringField;
    WideStringField57: TWideStringField;
    WideStringField58: TWideStringField;
    WideStringField59: TWideStringField;
    WideStringField60: TWideStringField;
    WideStringField61: TWideStringField;
    WideStringField62: TWideStringField;
    WideStringField63: TWideStringField;
    WideStringField64: TWideStringField;
    WideStringField65: TWideStringField;
    DateTimeField2: TDateTimeField;
    WideStringField66: TWideStringField;
    WideStringField67: TWideStringField;
    WideStringField68: TWideStringField;
    WideStringField69: TWideStringField;
    WideStringField70: TWideStringField;
    WideStringField71: TWideStringField;
    WideStringField72: TWideStringField;
    WideStringField73: TWideStringField;
    WideStringField74: TWideStringField;
    frmContactSrcdup: TDataSource;
    qryContactscopydup: TERPQuery;
    WideStringField75: TWideStringField;
    IntegerField9: TIntegerField;
    IntegerField10: TIntegerField;
    IntegerField11: TIntegerField;
    IntegerField12: TIntegerField;
    WideStringField76: TWideStringField;
    WideStringField77: TWideStringField;
    WideStringField78: TWideStringField;
    WideStringField79: TWideStringField;
    WideStringField80: TWideStringField;
    WideStringField81: TWideStringField;
    WideStringField82: TWideStringField;
    WideStringField83: TWideStringField;
    WideStringField84: TWideStringField;
    WideStringField85: TWideStringField;
    WideStringField86: TWideStringField;
    WideStringField87: TWideStringField;
    WideStringField88: TWideStringField;
    WideStringField89: TWideStringField;
    WideStringField90: TWideStringField;
    WideStringField91: TWideStringField;
    WideStringField92: TWideStringField;
    WideStringField93: TWideStringField;
    WideStringField94: TWideStringField;
    WideStringField95: TWideStringField;
    WideStringField96: TWideStringField;
    WideStringField97: TWideStringField;
    WideStringField98: TWideStringField;
    WideStringField99: TWideStringField;
    WideStringField100: TWideStringField;
    WideStringField101: TWideStringField;
    WideStringField102: TWideStringField;
    DateTimeField3: TDateTimeField;
    WideStringField103: TWideStringField;
    WideStringField104: TWideStringField;
    WideStringField105: TWideStringField;
    WideStringField106: TWideStringField;
    WideStringField107: TWideStringField;
    WideStringField108: TWideStringField;
    WideStringField109: TWideStringField;
    WideStringField110: TWideStringField;
    WideStringField111: TWideStringField;
    frmContactSrccopydup: TDataSource;
    qryCustomers: TERPQuery;
    qryCustomersPhone: TWideStringField;
    qryCustomersFaxNumber: TWideStringField;
    qryCustomersMobile: TWideStringField;
    qryCustomersAltPhone: TWideStringField;
    qryCustomersContact1Phone: TWideStringField;
    qryCustomersContact2Phone: TWideStringField;
    qryCustomersClientID: TAutoIncField;
    qryCustomersCompany: TWideStringField;
    qryCustomersABN: TWideStringField;
    qryCustomersFirstName: TWideStringField;
    qryCustomersMiddleName: TWideStringField;
    qryCustomersLastName: TWideStringField;
    qryCustomersPosition: TWideStringField;
    qryCustomersEmail: TWideStringField;
    qryCustomersAltContact: TWideStringField;
    qryCustomersContact1: TWideStringField;
    qryCustomersPhoneSupportTill: TDateField;
    qryCustomersContact2: TWideStringField;
    qryCustomersNotes: TWideMemoField;
    qryCustomersMedTypeID: TIntegerField;
    qryCustomersTYPE: TWideStringField;
    qryCustomersCreditLimit: TFloatField;
    qryCustomersBalance: TFloatField;
    qryCustomersTERMS: TWideStringField;
    qryCustomersTermsID: TIntegerField;
    qryCustomersShippingMethod: TWideStringField;
    qryCustomersShippingID: TIntegerField;
    qryCustomersDiscount: TFloatField;
    qryCustomersSpecialDiscount: TFloatField;
    qryCustomersJobName: TWideStringField;
    qryCustomersIsJob: TWideStringField;
    qryCustomersPayMethodID: TIntegerField;
    qryCustomersFeedback: TWideStringField;
    qryCustomersCustomer: TWideStringField;
    qryCustomersSupplier: TWideStringField;
    qryCustomersOtherContact: TWideStringField;
    qryCustomersOtherContactType: TIntegerField;
    qryCustomersRepID: TIntegerField;
    qryCustomersGlobal: TWideStringField;
    qryCustomersDone: TWideStringField;
    qryCustomersActive: TWideStringField;
    qryCustomersEditedFlag: TWideStringField;
    qryCustomersDontContact: TWideStringField;
    qryCustomersParentClientID: TIntegerField;
    qryCustomersGracePeriod: TSmallintField;
    qryCustomersClientNo: TWideStringField;
    qryCustomersTAXID: TIntegerField;
    qryCustomersTitle: TWideStringField;
    qryCustomersClientTypeID: TIntegerField;
    qryCustomersURL: TWideStringField;
    qryCustomersStopCredit: TWideStringField;
    qryCustomersRequired: TWideStringField;
    qryCustomersForcePOOnBooking: TWideStringField;
    qryCustomersForcePOOnInvoice: TWideStringField;
    qryCustomersPickingPriority: TIntegerField;
    qryCustomersDefaultInvoiceTemplateID: TIntegerField;
    qryCustomersRepName: TWideStringField;
    qryCustomersCardNumber: TWideStringField;
    qryCustomersGroupDiscountOverridesAll: TWideStringField;
    qryCustomersDefaultClass: TWideStringField;
    qryCustomersState: TWideStringField;
    qryCustomersStreet: TWideStringField;
    qryCustomersStreet2: TWideStringField;
    qryCustomersSuburb: TWideStringField;
    qryCustomersCountry: TWideStringField;
    qryCustomersPostcode: TWideStringField;
    qryCustomersBillStreet: TWideStringField;
    qryCustomersBillStreet2: TWideStringField;
    qryCustomersBillSuburb: TWideStringField;
    qryCustomersBillState: TWideStringField;
    qryCustomersBillCountry: TWideStringField;
    qryCustomersBillPostcode: TWideStringField;
    qryCustomersPOBox: TWideStringField;
    qryCustomersPOSuburb: TWideStringField;
    qryCustomersPOState: TWideStringField;
    qryCustomersPOCountry: TWideStringField;
    qryCustomersPOPostcode: TWideStringField;
    qryCustomersCUSTFLD1: TWideStringField;
    qryCustomersCUSTFLD2: TWideStringField;
    qryCustomersCUSTFLD3: TWideStringField;
    qryCustomersCUSTFLD4: TWideStringField;
    qryCustomersCUSTFLD5: TWideStringField;
    qryCustomersCUSTFLD6: TWideStringField;
    qryCustomersCUSTFLD7: TWideStringField;
    qryCustomersCUSTFLD8: TWideStringField;
    qryCustomersCUSTFLD9: TWideStringField;
    qryCustomersCUSTFLD10: TWideStringField;
    qryCustomersCUSTFLD11: TWideStringField;
    qryCustomersCUSTFLD12: TWideStringField;
    qryCustomersCUSTFLD13: TWideStringField;
    qryCustomersCUSTFLD14: TWideStringField;
    qryCustomersCUSTFLD15: TWideStringField;
    qryCustomersCreationDate: TDateField;
    qryCustomersDischargeDate: TDateField;
    qryCustomersArea: TSmallintField;
    qryCustomersJobTitle: TWideStringField;
    qryCustomersInvBaseNumber: TIntegerField;
    qryCustomersUseInvBase: TWideStringField;
    qryCustomersParentRelatedClientID: TIntegerField;
    qryCustomersDeliveryNotes: TWideMemoField;
    qryCustomersDefaultContactMethod: TWideStringField;
    qryCustomersCreditCardNumber: TWideStringField;
    qryCustomersCreditCardExpiryDate: TWideStringField;
    qryCustomersCreditCardNotes: TWideStringField;
    qryCustomersCreditCardType: TWideStringField;
    qryCustomersLastUpdated: TDateTimeField;
    qryCustomersBankAccountName: TWideStringField;
    qryCustomersBankAccountBSB: TWideStringField;
    qryCustomersBankAccountNo: TWideStringField;
    qryCustomersBankCode: TWideStringField;
    qryCustomersForeignExchangeSellCode: TWideStringField;
    qryCustomersCreditCardCardHolderName: TWideStringField;
    qryCustomersForcePOOnCustomer: TWideStringField;
    qryCustomersDefaultDeliveryTemplateID: TIntegerField;
    qryCustomersHours: TFloatField;
    qryCustomersEmailXML: TWideStringField;
    qryCustomersInvoiceComment: TWideMemoField;
    qryCustomersInvoiceCommentPopUp: TWideStringField;
    qryCustomersSendXMLInvoices: TWideStringField;
    qryCustomersStreet3: TWideStringField;
    qryCustomersBillStreet3: TWideStringField;
    qryCustomersIncludeOnIntrastat: TWideStringField;
    qryCustomersCUSTDATE1: TDateField;
    qryCustomersCUSTDATE2: TDateField;
    qryCustomersCUSTDATE3: TDateField;
    qryCustomersForcePOOnRepair: TWideStringField;
    qryCustomersGlobalref: TWideStringField;
    qryCustomersSpecialProductPriceOverridesAll: TWideStringField;
    qryCustomersPortOfLanding: TWideStringField;
    qryCustomersPortOfDischarge: TWideStringField;
    qryCustomersFinalDestination: TWideStringField;
    qryCustomersIncoPlace: TWideStringField;
    qryCustomersShippingAgentID: TIntegerField;
    qryCustomersDefaultStatementTemplateId: TIntegerField;
    qryCustomersCallPriority: TIntegerField;
    qryCustomersTeamviewerID: TWideStringField;
    qryCustomersSkypename: TWideStringField;
    frmCustomerSrc: TDataSource;
    qryCustomersCopy: TERPQuery;
    WideStringField112: TWideStringField;
    WideStringField113: TWideStringField;
    WideStringField114: TWideStringField;
    WideStringField115: TWideStringField;
    WideStringField116: TWideStringField;
    WideStringField117: TWideStringField;
    AutoIncField1: TAutoIncField;
    WideStringField118: TWideStringField;
    WideStringField119: TWideStringField;
    WideStringField120: TWideStringField;
    WideStringField121: TWideStringField;
    WideStringField122: TWideStringField;
    WideStringField123: TWideStringField;
    WideStringField124: TWideStringField;
    WideStringField125: TWideStringField;
    WideStringField126: TWideStringField;
    DateField1: TDateField;
    WideStringField127: TWideStringField;
    WideMemoField1: TWideMemoField;
    IntegerField13: TIntegerField;
    WideStringField128: TWideStringField;
    FloatField1: TFloatField;
    FloatField2: TFloatField;
    WideStringField129: TWideStringField;
    IntegerField14: TIntegerField;
    WideStringField130: TWideStringField;
    IntegerField15: TIntegerField;
    FloatField3: TFloatField;
    FloatField4: TFloatField;
    WideStringField131: TWideStringField;
    WideStringField132: TWideStringField;
    IntegerField16: TIntegerField;
    WideStringField133: TWideStringField;
    WideStringField134: TWideStringField;
    WideStringField135: TWideStringField;
    WideStringField136: TWideStringField;
    IntegerField17: TIntegerField;
    IntegerField18: TIntegerField;
    WideStringField137: TWideStringField;
    WideStringField138: TWideStringField;
    WideStringField139: TWideStringField;
    WideStringField140: TWideStringField;
    WideStringField141: TWideStringField;
    IntegerField19: TIntegerField;
    SmallintField1: TSmallintField;
    WideStringField142: TWideStringField;
    IntegerField20: TIntegerField;
    WideStringField144: TWideStringField;
    IntegerField21: TIntegerField;
    WideStringField145: TWideStringField;
    WideStringField146: TWideStringField;
    WideStringField147: TWideStringField;
    WideStringField148: TWideStringField;
    WideStringField149: TWideStringField;
    IntegerField22: TIntegerField;
    IntegerField23: TIntegerField;
    WideStringField150: TWideStringField;
    WideStringField151: TWideStringField;
    WideStringField152: TWideStringField;
    WideStringField153: TWideStringField;
    WideStringField154: TWideStringField;
    WideStringField155: TWideStringField;
    WideStringField156: TWideStringField;
    WideStringField157: TWideStringField;
    WideStringField158: TWideStringField;
    WideStringField159: TWideStringField;
    WideStringField160: TWideStringField;
    WideStringField161: TWideStringField;
    WideStringField162: TWideStringField;
    WideStringField163: TWideStringField;
    WideStringField164: TWideStringField;
    WideStringField165: TWideStringField;
    WideStringField166: TWideStringField;
    WideStringField167: TWideStringField;
    WideStringField168: TWideStringField;
    WideStringField169: TWideStringField;
    WideStringField170: TWideStringField;
    WideStringField171: TWideStringField;
    WideStringField172: TWideStringField;
    WideStringField173: TWideStringField;
    WideStringField174: TWideStringField;
    WideStringField175: TWideStringField;
    WideStringField176: TWideStringField;
    WideStringField177: TWideStringField;
    WideStringField178: TWideStringField;
    WideStringField179: TWideStringField;
    WideStringField180: TWideStringField;
    WideStringField181: TWideStringField;
    WideStringField182: TWideStringField;
    WideStringField183: TWideStringField;
    WideStringField184: TWideStringField;
    WideStringField185: TWideStringField;
    DateField2: TDateField;
    DateField3: TDateField;
    SmallintField2: TSmallintField;
    WideStringField186: TWideStringField;
    IntegerField24: TIntegerField;
    WideStringField187: TWideStringField;
    IntegerField25: TIntegerField;
    WideMemoField2: TWideMemoField;
    WideStringField188: TWideStringField;
    WideStringField189: TWideStringField;
    WideStringField190: TWideStringField;
    WideStringField191: TWideStringField;
    WideStringField192: TWideStringField;
    DateTimeField4: TDateTimeField;
    WideStringField193: TWideStringField;
    WideStringField194: TWideStringField;
    WideStringField195: TWideStringField;
    WideStringField196: TWideStringField;
    WideStringField197: TWideStringField;
    WideStringField198: TWideStringField;
    WideStringField199: TWideStringField;
    IntegerField26: TIntegerField;
    FloatField5: TFloatField;
    WideStringField200: TWideStringField;
    WideMemoField3: TWideMemoField;
    WideStringField201: TWideStringField;
    WideStringField202: TWideStringField;
    WideStringField203: TWideStringField;
    WideStringField204: TWideStringField;
    WideStringField205: TWideStringField;
    DateField4: TDateField;
    DateField5: TDateField;
    DateField6: TDateField;
    WideStringField206: TWideStringField;
    WideStringField207: TWideStringField;
    WideStringField208: TWideStringField;
    WideStringField209: TWideStringField;
    WideStringField210: TWideStringField;
    WideStringField211: TWideStringField;
    WideStringField212: TWideStringField;
    IntegerField27: TIntegerField;
    IntegerField29: TIntegerField;
    IntegerField30: TIntegerField;
    WideStringField217: TWideStringField;
    WideStringField218: TWideStringField;
    frmCustomerSrcCopy: TDataSource;
    Memo1: TMemo;
    Memo2: TMemo;
    ERPQuery1: TERPQuery;
    DataSource1: TDataSource;
    ERPQuery2: TERPQuery;
    WideStringField143: TWideStringField;
    AutoIncField2: TAutoIncField;
    IntegerField28: TIntegerField;
    IntegerField31: TIntegerField;
    IntegerField32: TIntegerField;
    WideStringField213: TWideStringField;
    WideStringField214: TWideStringField;
    WideStringField215: TWideStringField;
    WideStringField216: TWideStringField;
    WideStringField219: TWideStringField;
    WideStringField220: TWideStringField;
    WideStringField221: TWideStringField;
    WideStringField222: TWideStringField;
    WideStringField223: TWideStringField;
    WideStringField224: TWideStringField;
    WideStringField225: TWideStringField;
    WideStringField226: TWideStringField;
    WideStringField227: TWideStringField;
    WideStringField228: TWideStringField;
    WideStringField229: TWideStringField;
    WideStringField230: TWideStringField;
    WideStringField231: TWideStringField;
    WideStringField232: TWideStringField;
    WideStringField233: TWideStringField;
    qryContactsContactName: TWideStringField;
    WideStringField234: TWideStringField;
    WideStringField235: TWideStringField;
    WideStringField236: TWideStringField;
    WideStringField237: TWideStringField;
    WideStringField238: TWideStringField;
    qryContactscontactISCustomer_1: TWideStringField;
    WideStringField239: TWideStringField;
    WideStringField240: TWideStringField;
    WideStringField241: TWideStringField;
    DSContacts: TDataSource;
    procedure Button1Click(Sender: TObject);

  private
    MyConnectionCopy: TERPConnection;
      contact, contactcopy:Tcontact;

    procedure Dobusobjevent(Const Sender: TDatasetBusObj; const EventType, Value: string);
    procedure DobusobjeventCopy(Const Sender: TDatasetBusObj; const EventType, Value: string);

    procedure OpenConnections;
    procedure Createbusobj;
    procedure createCustomers;
    procedure Createcontacts;
    procedure updatecontactsusingbusobj;
    procedure updatecontactsusingbusobjCopy;
    Procedure Memo2Linesadd(const Value:String);
    Procedure Memo1Linesadd(const Value:String);
  public
    { Public declarations }
  end;


implementation

uses BusObjConst, CommonDbLib, CommonLib;

{$R *.dfm}
procedure Tfmrestcontact.Dobusobjevent(const Sender: TDatasetBusObj;
  const EventType, Value: string);
begin
  if (Eventtype = BusObjEvent_Dataset) and (Value = BusObjEvent_AssignDataset) then begin
    if Sender is TContact then TContact(Sender).DataSet := qryContacts;
  end;

end;

procedure Tfmrestcontact.DobusobjeventCopy(const Sender: TDatasetBusObj;
  const EventType, Value: string);
begin
  if (Eventtype = BusObjEvent_Dataset) and (Value = BusObjEvent_AssignDataset) then begin
    if Sender is TContact then TContact(Sender).DataSet := qryContactsCopy;
  end;

end;


procedure Tfmrestcontact.Memo1Linesadd(const Value: String);
begin
  Memo1.Lines.Add(Value);
end;

procedure Tfmrestcontact.Memo2Linesadd(const Value: String);
begin
  Memo2.Lines.Add(Value);
end;

procedure Tfmrestcontact.Button1Click(Sender: TObject);
begin
  Memo1.lines.clear;
  Memo2.lines.clear;
    OpenConnections;
    Createbusobj;
    createCustomers;
    Createcontacts;
    updatecontactsusingbusobj;
    updatecontactsusingbusobjCopy;
end;
procedure Tfmrestcontact.OpenConnections;
begin
  MyConnectionCopy := GetNewMyDacConnection(self);
  closedb(qryContacts);
  closeDb(qryContactsdup);
  closedb(qryContactsCopy);
  closeDb(qryContactsCopydup);
  closedb(qryCustomers);
  closeDb(qryCustomerscopy);
  qryCustomers.connection:= MyConnection;
  qryCustomerscopy.connection:= MyConnectioncopy;
  qryContacts.connection := MyConnection;
  qryContactsdup.connection := MyConnection;
  qryContactsCopy.connection := MyConnectioncopy;
  qryContactsCopydup.connection := MyConnectioncopy;
end;

procedure Tfmrestcontact.Createbusobj;
begin
  contact:= Tcontact.create(Self);
  contact.connection := TMydacdataconnection.create(contact);
  contact.connection.connection := MyConnection;
  contact.BusobjEvent :=DoBusobjEvent;

  contactCopy:= Tcontact.create(Self);
  contactCopy.connection := TMydacdataconnection.create(contactCopy);
  contactCopy.connection.connection := MyConnectionCopy;
  contactCopy.BusobjEvent :=DoBusobjEventcopy;

  contact.Connection.BeginTransaction;
  contactCopy.Connection.BeginTransaction;
end;
procedure Tfmrestcontact.createCustomers;
begin

  qryContacts.Parambyname('keyID').asInteger :=0;
  qryContactsdup.Parambyname('keyID').asInteger :=0;
  qryContactscopy.Parambyname('keyID').asInteger :=0;
  qryContactscopydup.Parambyname('keyID').asInteger :=0;

  qryCustomers.Parambyname('cusid').asInteger :=0;
  qryCustomersCopy.Parambyname('cusid').asInteger :=0;
  qryCustomers.OPEN;
  qryCustomersCopy.oPEN;

  qryCustomers.Append;
  qryCustomers.fieldbyname('Firstname').asString  :='aa';
  qryCustomers.fieldbyname('Company').asString := 'aa';
  qryCustomers.Post;
  Memo1Linesadd('New customer :' +inttostr(Qrycustomers.FieldByname('clientId').asInteger));

  qryCustomersCopy.Append;
  qryCustomersCopy.fieldbyname('Firstname').asString  :='ss';
  qryCustomersCopy.fieldbyname('Company').asString := 'ss';
  qryCustomersCopy.Post;
  Memo2Linesadd('New customer :' +inttostr(QrycustomersCopy.FieldByname('clientId').asInteger));
end;

procedure Tfmrestcontact.Createcontacts;
begin
  opendb(qryContactsdup);
  qryContactsdup.Append;
  qryContactsdup.FieldByname('CusId').asInteger                :=  Qrycustomers.FieldByname('clientId').asInteger;
  qryContactsdup.FieldByname('ContactTitle').asString          :=  Qrycustomers.FieldByname('Title').asString;
  qryContactsdup.FieldByname('ContactFirstName').asString      :=  Qrycustomers.FieldByname('FirstName').asString;
  qryContactsdup.FieldByname('ContactSurName').asString        :=  Qrycustomers.FieldByname('LastName').asString;
  qryContactsdup.FieldByname('ContactMOB').asString            :=  Qrycustomers.FieldByname('Mobile').asString;
  qryContactsdup.FieldByname('jobtitle').asString              :=  Qrycustomers.FieldByname('JobTitle').asString;
  qryContactsdup.FieldByname('ContactEmail').asString          :=  Qrycustomers.FieldByname('Email').asString;
  qryContactsdup.FieldByname('Company').asString               :=  Qrycustomers.FieldByname('FirstName').asString+' ' +Qrycustomers.FieldByname('LastName').asString;
  qryContactsdup.FieldByname('ContactPH').asString             :=  Qrycustomers.FieldByname('Phone').asString;
  qryContactsdup.FieldByname('ContactFax').asString            :=  Qrycustomers.FieldByname('FaxNumber').asString;
  qryContactsdup.FieldByname('ContactAltPH').asString          :=  Qrycustomers.FieldByname('AltPhone').asString;
  qryContactsdup.FieldByname('ContactAddress').asString        :=  Qrycustomers.FieldByname('Street').asString;
  qryContactsdup.FieldByname('ContactAddress2').asString       :=  Qrycustomers.FieldByname('Street2').asString;
  qryContactsdup.FieldByname('ContactCity').asString           :=  Qrycustomers.FieldByname('Suburb').asString;
  qryContactsdup.FieldByname('ContactState').asString          :=  Qrycustomers.FieldByname('State').asString;
  qryContactsdup.FieldByname('ContactPcode').asString          :=  Qrycustomers.FieldByname('Postcode').asString;
  qryContactsdup.FieldByname('Contactcountry').asString        :=  Qrycustomers.FieldByname('Country').asString;
  qryContactsdup.FieldByname('ISPrimaryContact').asBoolean     := True;
  qryContactsdup.FieldByname('ContactIsOtherContact').asBoolean:= False;
  qryContactsdup.FieldByname('ContactIsJob').asBoolean         := False;
  qryContactsdup.FieldByname('Active').asBoolean               := True;
  qryContactsdup.FieldByname('ContactIsCustomer').asBoolean    := True;
  qryContactsdup.FieldByname('ContactIsSupplier').asBoolean    := Qrycustomers.FieldByname('supplier').asboolean;
  qryContactsdup.Post;
  Memo1Linesadd('New contact :' +inttostr(qryContactsdup.fieldByname('contactID').asInteger));


  opendb(qryContactscopydup);
  qryContactscopydup.Append;
  qryContactscopydup.FieldByname('CusId').asInteger                :=  QrycustomersCopy.FieldByname('clientId').asInteger;
  qryContactscopydup.FieldByname('ContactTitle').asString          :=  QrycustomersCopy.FieldByname('Title').asString;
  qryContactscopydup.FieldByname('ContactFirstName').asString      :=  QrycustomersCopy.FieldByname('FirstName').asString;
  qryContactscopydup.FieldByname('ContactSurName').asString        :=  QrycustomersCopy.FieldByname('LastName').asString;
  qryContactscopydup.FieldByname('ContactMOB').asString            :=  QrycustomersCopy.FieldByname('Mobile').asString;
  qryContactscopydup.FieldByname('jobtitle').asString              :=  QrycustomersCopy.FieldByname('JobTitle').asString;
  qryContactscopydup.FieldByname('ContactEmail').asString          :=  QrycustomersCopy.FieldByname('Email').asString;
  qryContactscopydup.FieldByname('Company').asString               :=  QrycustomersCopy.FieldByname('FirstName').asString+' ' +QrycustomersCopy.FieldByname('LastName').asString;
  qryContactscopydup.FieldByname('ContactPH').asString             :=  QrycustomersCopy.FieldByname('Phone').asString;
  qryContactscopydup.FieldByname('ContactFax').asString            :=  QrycustomersCopy.FieldByname('FaxNumber').asString;
  qryContactscopydup.FieldByname('ContactAltPH').asString          :=  QrycustomersCopy.FieldByname('AltPhone').asString;
  qryContactscopydup.FieldByname('ContactAddress').asString        :=  QrycustomersCopy.FieldByname('Street').asString;
  qryContactscopydup.FieldByname('ContactAddress2').asString       :=  QrycustomersCopy.FieldByname('Street2').asString;
  qryContactscopydup.FieldByname('ContactCity').asString           :=  QrycustomersCopy.FieldByname('Suburb').asString;
  qryContactscopydup.FieldByname('ContactState').asString          :=  QrycustomersCopy.FieldByname('State').asString;
  qryContactscopydup.FieldByname('ContactPcode').asString          :=  QrycustomersCopy.FieldByname('Postcode').asString;
  qryContactscopydup.FieldByname('Contactcountry').asString        :=  QrycustomersCopy.FieldByname('Country').asString;
  qryContactscopydup.FieldByname('ISPrimaryContact').asBoolean     := True;
  qryContactscopydup.FieldByname('ContactIsOtherContact').asBoolean:= False;
  qryContactscopydup.FieldByname('ContactIsJob').asBoolean         := False;
  qryContactscopydup.FieldByname('Active').asBoolean               := True;
  qryContactscopydup.FieldByname('ContactIsCustomer').asBoolean    := True;
  qryContactscopydup.FieldByname('ContactIsSupplier').asBoolean    := QrycustomersCopy.FieldByname('supplier').asboolean;
  qryContactscopydup.Post;
  Memo2Linesadd('New contact :' +inttostr(qryContactscopydup.fieldByname('contactID').asInteger));
end;
procedure Tfmrestcontact.updatecontactsusingbusobj;
begin
  Memo1Linesadd('busobj contact opening contact : ' +inttostr(qryContactsdup.fieldByname('contactID').asInteger));
  contact.Load(qryContactsdup.Fieldbyname(contact.Idfieldname).asInteger);
  Memo1Linesadd('busobj contact Opened contact : ' +inttostr(qryContactsdup.fieldByname('contactID').asInteger));
  contact.connection.BeginNestedTransaction;
  Memo1Linesadd('begin nested transaction ');
  contact.company := contact.ContactFirstName+' ' +contact.ContactSurName+ ' changed';
  Memo1Linesadd('busobj contact company changed : ' +contact.company );
  contact.PostDB;
  Memo1Linesadd('busobj contact :Posted');
end;

procedure Tfmrestcontact.updatecontactsusingbusobjCopy;
begin
  Memo2Linesadd('busobj contact opening contact : ' +inttostr(qryContactscopydup.fieldByname('contactID').asInteger));
  contactCopy.Load(qryContactscOPYdup.Fieldbyname(contactCopy.Idfieldname).asInteger);
  Memo2Linesadd('busobj contact Opened contact : ' +inttostr(qryContactscopydup.fieldByname('contactID').asInteger));
  contactCopy.connection.BeginNestedTransaction;
  Memo2Linesadd('begin nested transaction ');
  contactCopy.company := contactCopy.ContactFirstName+' ' +contact.ContactSurName+ ' changed';
  Memo2Linesadd('busobj contact company changed : ' +contactcopy.company );
  contactCopy.PostDB;
  Memo2Linesadd('busobj contact :Posted');
end;


initialization
  RegisterClassOnce(Tfmrestcontact);
end.

