inherited fmProdAttribCustomfields: TfmProdAttribCustomfields
  Left = 843
  Top = 316
  Caption = 'Product Attibute Custom Fields'
  ClientHeight = 405
  ClientWidth = 831
  ExplicitLeft = 843
  ExplicitTop = 316
  ExplicitWidth = 839
  ExplicitHeight = 432
  PixelsPerInch = 96
  TextHeight = 13
  HelpContext = 1206002
  inherited lblSkingroupMsg: TLabel
    Top = 405
    Width = 831
    ExplicitTop = 405
    ExplicitWidth = 831
    HelpContext = 1206003
  end
  object Subform: TDNMPanel [3]
    Left = 0
    Top = 0
    Width = 831
    Height = 405
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    HelpContext = 1206004
    object pnlCustFields: TDNMPanel
      Left = 1
      Top = 1
      Width = 829
      Height = 403
      HelpContext = 1206005
      Align = alClient
      BevelOuter = bvNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Transparent = False
      ExplicitLeft = 2
      ExplicitTop = -4
      object Bevel1: TBevel
        Left = 312
        Top = 7
        Width = 206
        Height = 32
        HelpContext = 1206006
        Style = bsRaised
      end
      object Box181: TBevel
        Left = 28
        Top = 51
        Width = 776
        Height = 247
        HelpContext = 1206007
      end
      object Label1: TLabel
        Left = 317
        Top = 12
        Width = 193
        Height = 26
        HelpContext = 1206008
        AutoSize = False
        Caption = 'Customisable Fields'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
        WordWrap = True
      end
      object CUSTLBL1: TLabel
        Left = 122
        Top = 74
        Width = 17
        Height = 15
        HelpContext = 1206009
        Alignment = taRightJustify
        Caption = 'cl1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL2: TLabel
        Left = 122
        Top = 112
        Width = 17
        Height = 15
        HelpContext = 1206010
        Alignment = taRightJustify
        Caption = 'cl2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL3: TLabel
        Left = 122
        Top = 151
        Width = 17
        Height = 15
        HelpContext = 1206011
        Alignment = taRightJustify
        Caption = 'cl3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL4: TLabel
        Left = 122
        Top = 189
        Width = 17
        Height = 15
        HelpContext = 1206012
        Alignment = taRightJustify
        Caption = 'cl4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL5: TLabel
        Left = 122
        Top = 228
        Width = 17
        Height = 15
        HelpContext = 1206013
        Alignment = taRightJustify
        Caption = 'cl5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL6: TLabel
        Left = 122
        Top = 267
        Width = 17
        Height = 15
        HelpContext = 1206014
        Alignment = taRightJustify
        Caption = 'cl6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL7: TLabel
        Left = 381
        Top = 74
        Width = 17
        Height = 15
        HelpContext = 1206015
        Alignment = taRightJustify
        Caption = 'cl7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL8: TLabel
        Left = 381
        Top = 112
        Width = 17
        Height = 15
        HelpContext = 1206016
        Alignment = taRightJustify
        Caption = 'cl8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL9: TLabel
        Left = 381
        Top = 151
        Width = 17
        Height = 15
        HelpContext = 1206017
        Alignment = taRightJustify
        Caption = 'cl9'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL10: TLabel
        Left = 374
        Top = 189
        Width = 24
        Height = 15
        HelpContext = 1206018
        Alignment = taRightJustify
        Caption = 'cl10'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL11: TLabel
        Left = 374
        Top = 228
        Width = 23
        Height = 15
        HelpContext = 1206019
        Alignment = taRightJustify
        Caption = 'cl11'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL12: TLabel
        Left = 373
        Top = 267
        Width = 24
        Height = 15
        HelpContext = 1206020
        Alignment = taRightJustify
        Caption = 'cl12'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL13: TLabel
        Left = 633
        Top = 74
        Width = 24
        Height = 15
        HelpContext = 1206021
        Alignment = taRightJustify
        Caption = 'cl13'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL14: TLabel
        Left = 633
        Top = 112
        Width = 24
        Height = 15
        HelpContext = 1206022
        Alignment = taRightJustify
        Caption = 'cl14'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL15: TLabel
        Left = 633
        Top = 151
        Width = 24
        Height = 15
        HelpContext = 1206023
        Alignment = taRightJustify
        Caption = 'cl15'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL16: TLabel
        Left = 633
        Top = 189
        Width = 24
        Height = 15
        HelpContext = 1206024
        Alignment = taRightJustify
        Caption = 'cl16'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object Label2: TLabel
        Left = 631
        Top = 215
        Width = 3
        Height = 15
        HelpContext = 1206025
        Alignment = taRightJustify
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object Label3: TLabel
        Left = 631
        Top = 247
        Width = 3
        Height = 15
        HelpContext = 1206026
        Alignment = taRightJustify
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL17: TLabel
        Left = 633
        Top = 228
        Width = 24
        Height = 15
        HelpContext = 1206027
        Alignment = taRightJustify
        Caption = 'cl17'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object CUSTLBL18: TLabel
        Left = 633
        Top = 267
        Width = 24
        Height = 15
        HelpContext = 1206028
        Alignment = taRightJustify
        Caption = 'cl18'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        Transparent = True
      end
      object Label4: TLabel
        Left = 30
        Top = 356
        Width = 100
        Height = 15
        HelpContext = 1206029
        Caption = 'Template Product'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object cmdCustomLabelsOld: TDNMSpeedButton
        Left = 377
        Top = 309
        Width = 87
        Height = 27
        Hint = '"Add A New Customised Field For All Employee'#39's"'
        HelpContext = 1206030
        Caption = '&Add Labels'
        DisableTransparent = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        HotTrackFont.Charset = DEFAULT_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -12
        HotTrackFont.Name = 'Arial'
        HotTrackFont.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 18
        OnClick = cmdCustomLabelsOldClick
      end
      object CUSTFLD1: TwwDBComboBox
        Left = 142
        Top = 70
        Width = 130
        Height = 23
        HelpContext = 1206031
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD1'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 0
        UnboundDataType = wwDefault
      end
      object CUSTFLD2: TwwDBComboBox
        Left = 142
        Top = 108
        Width = 130
        Height = 23
        HelpContext = 1206032
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD2'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 1
        UnboundDataType = wwDefault
      end
      object CUSTFLD3: TwwDBComboBox
        Left = 142
        Top = 147
        Width = 130
        Height = 23
        HelpContext = 1206033
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD3'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 2
        UnboundDataType = wwDefault
      end
      object CUSTFLD4: TwwDBComboBox
        Left = 142
        Top = 185
        Width = 130
        Height = 23
        HelpContext = 1206034
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD4'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 3
        UnboundDataType = wwDefault
      end
      object CUSTFLD5: TwwDBComboBox
        Left = 142
        Top = 224
        Width = 130
        Height = 23
        HelpContext = 1206035
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD5'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 4
        UnboundDataType = wwDefault
      end
      object CUSTFLD10: TwwDBComboBox
        Left = 401
        Top = 185
        Width = 130
        Height = 23
        HelpContext = 1206036
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD10'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 9
        UnboundDataType = wwDefault
      end
      object CUSTFLD9: TwwDBComboBox
        Left = 401
        Top = 147
        Width = 130
        Height = 23
        HelpContext = 1206037
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD9'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 8
        UnboundDataType = wwDefault
      end
      object CUSTFLD8: TwwDBComboBox
        Left = 401
        Top = 108
        Width = 130
        Height = 23
        HelpContext = 1206038
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD8'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 7
        UnboundDataType = wwDefault
      end
      object CUSTFLD7: TwwDBComboBox
        Left = 401
        Top = 70
        Width = 130
        Height = 23
        HelpContext = 1206039
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD7'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 6
        UnboundDataType = wwDefault
      end
      object CUSTFLD6: TwwDBComboBox
        Left = 142
        Top = 263
        Width = 130
        Height = 23
        HelpContext = 1206040
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD6'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 5
        UnboundDataType = wwDefault
      end
      object CUSTFLD11: TwwDBComboBox
        Left = 401
        Top = 224
        Width = 130
        Height = 23
        HelpContext = 1206041
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD11'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 10
        UnboundDataType = wwDefault
      end
      object CUSTFLD12: TwwDBComboBox
        Left = 401
        Top = 263
        Width = 130
        Height = 23
        HelpContext = 1206042
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD12'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 11
        UnboundDataType = wwDefault
      end
      object CUSTFLD13: TwwDBComboBox
        Left = 660
        Top = 70
        Width = 130
        Height = 23
        HelpContext = 1206043
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD13'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 12
        UnboundDataType = wwDefault
      end
      object CUSTFLD14: TwwDBComboBox
        Left = 660
        Top = 108
        Width = 130
        Height = 23
        HelpContext = 1206044
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD14'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 13
        UnboundDataType = wwDefault
      end
      object CUSTFLD15: TwwDBComboBox
        Left = 660
        Top = 147
        Width = 130
        Height = 23
        HelpContext = 1206045
        ShowButton = True
        Style = csDropDown
        MapList = False
        AllowClearKey = False
        DataField = 'CUSTFLD15'
        DropDownCount = 8
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ButtonWidth = -1
        ItemHeight = 0
        ParentFont = False
        Sorted = False
        TabOrder = 14
        UnboundDataType = wwDefault
      end
      object CUSTFLD16: TwwDBDateTimePicker
        Left = 660
        Top = 185
        Width = 130
        Height = 23
        HelpContext = 1206046
        CalendarAttributes.Font.Charset = DEFAULT_CHARSET
        CalendarAttributes.Font.Color = clWindowText
        CalendarAttributes.Font.Height = -11
        CalendarAttributes.Font.Name = 'MS Sans Serif'
        CalendarAttributes.Font.Style = []
        DataField = 'CUSTDATE1'
        Epoch = 1950
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ShowButton = True
        TabOrder = 15
      end
      object CUSTFLD17: TwwDBDateTimePicker
        Left = 660
        Top = 224
        Width = 130
        Height = 23
        HelpContext = 1206047
        CalendarAttributes.Font.Charset = DEFAULT_CHARSET
        CalendarAttributes.Font.Color = clWindowText
        CalendarAttributes.Font.Height = -11
        CalendarAttributes.Font.Name = 'MS Sans Serif'
        CalendarAttributes.Font.Style = []
        DataField = 'CUSTDATE2'
        Epoch = 1950
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ShowButton = True
        TabOrder = 16
      end
      object CUSTFLD18: TwwDBDateTimePicker
        Left = 660
        Top = 263
        Width = 130
        Height = 23
        HelpContext = 1206048
        CalendarAttributes.Font.Charset = DEFAULT_CHARSET
        CalendarAttributes.Font.Color = clWindowText
        CalendarAttributes.Font.Height = -11
        CalendarAttributes.Font.Name = 'MS Sans Serif'
        CalendarAttributes.Font.Style = []
        DataField = 'CUSTDATE3'
        Epoch = 1950
        Enabled = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        ShowButton = True
        TabOrder = 17
      end
      object cboTemplateProduct: TwwDBLookupCombo
        Left = 142
        Top = 352
        Width = 345
        Height = 23
        HelpContext = 1206049
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = []
        DropDownAlignment = taLeftJustify
        Selected.Strings = (
          'PartName'#9'60'#9'PartName'#9'F')
        LookupTable = qtyTemplateProducts
        LookupField = 'PartsId'
        ParentFont = False
        TabOrder = 19
        AutoDropDown = False
        ShowButton = True
        PreciseEditRegion = False
        AllowClearKey = False
      end
      object bntUpdateCustomFields: TDNMSpeedButton
        Left = 493
        Top = 350
        Width = 311
        Height = 27
        HelpContext = 1206050
        Caption = 'Update custom Fields from the Selected Product'
        DisableTransparent = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -12
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        HotTrackFont.Charset = DEFAULT_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -12
        HotTrackFont.Name = 'Arial'
        HotTrackFont.Style = []
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 20
        OnClick = bntUpdateCustomFieldsClick
      end
    end
  end
  inherited tmrProcessMessage: TTimer
    Left = 521
    Top = 195
  end
  inherited tmrdelay: TTimer
    Left = 564
    Top = 195
  end
  inherited popSpelling: TPopupMenu
    Left = 608
    Top = 195
  end
  object qtyTemplateProducts: TERPQuery
    Connection = fmProdAttribMain.MyConnection
    SQL.Strings = (
      'SELECT distinct P.PartsId, P.PartName '
      
        'from tblproductattributeproducts pap inner join tblParts as P on' +
        ' P.PartsId = pap.ProductID and pap.PAG_ID =:GroupID'
      'Order by PartName')
    Left = 196
    Top = 26
    ParamData = <
      item
        DataType = ftUnknown
        Name = 'GroupID'
      end>
    object qtyTemplateProductsPartName: TWideStringField
      DisplayWidth = 60
      FieldName = 'PartName'
      Size = 60
    end
    object qtyTemplateProductsPartsId: TIntegerField
      FieldName = 'PartsId'
      Visible = False
    end
  end
end
