{CompanyInfo}
SELECT  
CO.CompanyName, 
CO.Address, 
CO.Address2, 
CO.City, 
CO.State, 
CO.Postcode, 
CO.PhoneNumber AS PhoneNumber, 
CO.FaxNumber AS FaxNumber, 
CO.ABN,   
concat('Ph: ', CO.PhoneNumber) AS Phone, 
concat('Fax: ' , CO.FaxNumber) AS Fax, 
concat('Email: ' , CO.email) as EmailAddress, 
CO.URL, 
concat('Website: ' , CO.URL) as WebAddress, 
Concat (if(ifnull(CO.CompanyName,'') <> '' , concat(CO.CompanyName , '
'), ''),if(ifnull(CO.Address,'') <> '' , concat(CO.Address,   '
'), ''),if(ifnull(CO.Address2,'') <> '' , concat(CO.Address2 , '
'), ''),if(ifnull(CO.City,'') <> '' , concat(CO.City , '
'), ''),if(ifnull(CO.State,'') <> '' , concat(CO.State , '
'), ''),if(ifnull(CO.Postcode,'') <> '' , concat(CO.Postcode , '
'), '')) NamenAddress,concat_ws(', ',  nullif(CO.Address, ''),  nullif(CO.Address2, ''), nullif(CO.Address3, ''), nullif(CO.City  , ''),  nullif(concat(CO.State  , ' '  , CO.postCode  ),'') , nullif(CO.country  , '') ) as CompAddress, 
concat_ws(', ',  nullif(CO.POBox  , ''),  nullif(CO.POBox2  , ''), nullif(CO.POBox3  , ''), nullif(CO.POCity, ''),  nullif(concat(CO.POState, ' '  , CO.POPostcode),'') , nullif(CO.POCountry, '') ) as CompbillAddress , CO.email , 'Admin ERP' as LoggedInUser ,
'Department' as ClassHeading ,
'M' as ProductAttrib1Name ,
'Weight' as ProductAttrib2Name ,
'Product ID' as PartColumn ,
'Group 1' as FirstColumn ,
'Group 2' as SecondColumn ,
'Group 3' as ThirdColumn, 
'Customer ID' as CustomerColumnName, 
'Supplier ID' as SupplierColumnName, 
'Prospect ID' as ProspectColumnName, 
'Print Name' as ProductPrintNameHeading, 
'Print Name' as ClientPrintNameHeading, 
'Batch No' as AllocationBatchnoName, 
'Expiry Date' as AllocationExpiryDateName, 
'Truck Load No' as AllocationTruckLoadNoName ,
'Equipment' as EquipmentName, 
'Hire' as HireName, 
'<Not Selected>' as RetailcustomerType1, 
'<Not Selected>' as WholeSaleCustomerType1, 
'<Not Selected>' as WholeSaleCustomerType2, 
'<Not Selected>' as WholeSaleCustomerType3, 
'<Not Selected>' as WholeSaleCustomerType4 ,  
'Weight' as PackWeightField1 , 
'Length' as PackWeightField2   
FROM tblCompanyInformation AS CO  
~|||~{invoicefooter}
SELECT 
Invoice_Footer from vinvoicefooterpref  
~|||~{Details}
SELECT  
P.ProductComment, 
CONCAT_WS(' ', c.Title, c.FirstName,c.LastName) as CompanyContact,           
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.UnitofMeasureSaleLines) as UnitofMeasure,           
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.UnitofMeasureShipped) as UnitofMeasureShipped,                   
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.UnitofMeasureBackorder) as UnitofMeasureBackorder,             
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.TotalLineAmount/d3.UnitofMeasureShipped) as UnitofMeasureLinePrice,         
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.TotalLineAmountInc/d3.UnitofMeasureShipped) as UnitofMeasureLinePriceInc,          
IF (d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T', '*', d3.ProductName) as ProductName,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.Shipped) as Shipped,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.BackOrder) as BackOrder,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.Product_Description) as Product_Description,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.LinePrice) as LinePrice,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.LineTax) as LineTax,                 
IF ((d3.IsRelatedProduct = 'T' AND d5.HideRelated = 'T') OR (P.HideOnPrint = 'T'), NULL,  d3.TotalLineAmountInc) as TotalLineAmountInc,                
(Price1+(Price1*LineTaxRate)) as OrgLinePriceInc,          
(100-DisCountPercent) as RebatePercent ,              
If(InStr(P.PRODUCTGROUP,'^') -1 >0,  Left(P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')-1),  P.PRODUCTGROUP) AS PartHeader,            
MID(P.PRODUCTGROUP, InStr(P.PRODUCTGROUP,'^')+1 ,  If(LOCATE('^',P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')+1) - InStr(P.PRODUCTGROUP,'^') >0,  LOCATE('^',P.PRODUCTGROUP,  InStr(P.PRODUCTGROUP,'^')+1)-1 - InStr(P.PRODUCTGROUP,'^'),  IF(InStr(P.PRODUCTGROUP,'^')<>0,CHAR_LENGTH(P.PRODUCTGROUP) - InStr(P.PRODUCTGROUP,'^'),0)))  AS PartSubLevel1,            
If((LOCATE('^',P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')+1)) >0,  MID(P.PRODUCTGROUP,LOCATE('^',P.PRODUCTGROUP, InStr(P.PRODUCTGROUP,'^')+1)+1,CHAR_LENGTH(P.PRODUCTGROUP)-  LOCATE('^',P.PRODUCTGROUP,  InStr(P.PRODUCTGROUP,'^')+1)),  Null)  AS PartSubLevel2,      
if(d2.Paid='T','YES','NO') as Paid2,               
SUBSTRING_INDEX( c.Company,'^',1) as Company_NoJobName,     
P.Price1 as 'ListPrice(Ex)',                
c.Company as Company,  
c.ABN as ABN,  
c.Title as Title,  
c.FirstName as FirstName,    
c.MiddleName as MiddleName,  
c.LastName as LastName,      
c.Position as POSITION,  
c.Street as Street,    
c.Street2 as Street2,  
c.Suburb as Suburb,  
c.State as State,  
c.Country as Country,  
c.Postcode as Postcode,        
c.BillStreet as BillStreet,  
c.BillStreet2 as BillStreet2,  
c.BillSuburb as BillSuburb,    
c.BillState as BillState,  
c.BillCountry as BillCountry,      
c.BillPostcode as BillPostcode,  
c.POBox as POBox,    
c.POSuburb as POSuburb,  
c.POState as POState,  
c.POCountry as POCountry,  
c.POPostcode as POPostcode,        
c.Phone as Phone,  
c.FaxNumber as FaxNumber,  
c.Mobile as Mobile,  
c.Email as Email,    
c.AltContact as AltContact,  
c.AltPhone as AltPhone,      
c.PhoneSupportTill as PhoneSupportTill,    
c.Contact1 as Contact1,  
c.Contact2 as Contact2,  
c.Contact1Phone as Contact1Phone,  
c.Contact2Phone as Contact2Phone,        
c.CreationDate as CreationDate,  
c.UpdateDate as UpdateDate,  
c.DateInactive as DateInactive,    
c.Notes as Notes,  
c.ClientNo as ClientNo,  
c.JobName as JobName,        
c.CUSTFLD1 as CUSTFLD1,  
c.CUSTFLD2 as CUSTFLD2,  
c.CUSTFLD3 as CUSTFLD3,  
c.CUSTFLD4 as CUSTFLD4,  
c.CUSTFLD5 as CUSTFLD5,  
c.CUSTFLD6 as CUSTFLD6,  
c.CUSTFLD7 as CUSTFLD7,      
c.CUSTFLD8 as CUSTFLD8,  
c.CUSTFLD9 as CUSTFLD9,  
c.CUSTFLD10 as CUSTFLD10,  
c.CUSTFLD11 as CUSTFLD11,  
c.CUSTFLD12 as CUSTFLD12,  
c.CUSTFLD13 as CUSTFLD13,  
c.CUSTFLD14 as CUSTFLD14,      
c.CUSTFLD15 as CUSTFLD15,           
d2.*, 
d3.*, 
concat_ws('-', d3.Productname, if(length(d3.SalesLinesCustField1)<=0 , null , d3.SalesLinesCustField1)) as ProductnamenCustFld1 ,
concat_ws('-', d3.ProductPrintName, if(length(d3.SalesLinesCustField1)<=0 , null , d3.SalesLinesCustField1)) as PrintProductnamenCustFld1 , 
concat_ws('-', d3.Productname, if(length(d3.SalesLinesCustField1)<=0 , null , d3.SalesLinesCustField1)) as ProductnamenCustFld1 ,
concat_ws('-', d3.ProductPrintName, if(length(d3.SalesLinesCustField1)<=0 , null , d3.SalesLinesCustField1)) as PrintProductnamenCustFld1,
d3.orglineprice+ d3.orglineprice* d3.linetaxrate as  orglinepriceinc,  
Concat('Transit-', d2.SaleID) AS InTransitBarcode,     
Concat('Ship-', d2.SaleID) AS ShippingtBarcode,  
UOM.Height  as Height, 
UOM.Width  as Width, 
UOM.Length  as LENGTH,   
UOM.Weight  as Weight, 
UOM.Volume  as Volume,        
d3.UnitofMeasureShipped * UOM.Length as shippedLength,  
d3.UnitofMeasureShipped * UOM.Weight as shippedWeight,   
d3.UnitofMeasureShipped * UOM.Height as shippedHeight,    
d3.UnitofMeasureShipped * UOM.Width as shippedWidth,      
d3.UnitofMeasureShipped *  UOM.Volume as shippedVolume,   
d3.UnitofMeasureShipped *  UOM.Volume * :CubicMeterToBroadFeet as shippedVolumeinBoardFeet,    
P.CUSTFLD1 as ProdCustFld1, 
P.CUSTFLD2 as ProdCustFld2,   
P.CUSTFLD3 as ProdCustFld3, 
P.CUSTFLD4 as ProdCustFld4,    
P.CUSTFLD5 as ProdCustFld5, 
P.CUSTFLD6 as ProdCustFld6, 
P.CUSTFLD7 as ProdCustFld7, 
P.CUSTFLD8 as ProdCustFld8,      
P.CUSTFLD9 as ProdCustFld9, 
P.CUSTFLD10 as ProdCustFld10, 
P.CUSTFLD11 as ProdCustFld11, 
P.CUSTFLD12 as ProdCustFld12,      
P.CUSTFLD13 as ProdCustFld13, 
P.CUSTFLD14 as ProdeCustFld14, 
P.CUSTFLD15 as ProdCustFld15, 
P.CUSTDATE1 as ProdCustDate1,      
P.CUSTDATE2 as ProdCustDate2, 
P.CUSTDATE3 as ProdCustDate3, 
PP.partPic as ProductPicture,  
Concat('S-',d2.SaleID) as SaleBarcode, 
P.BARCODE as ProductBarcode, 
Wt.GrossWeight, 
Wt.NetWeight,
c.DeliveryNotes  
FROM tblSales d2                   
INNER JOIN tblSalesLines d3 Using(SaleID)                         
inner join tblunitsofmeasure UOM on UOM.UnitID = d3.UnitOfMeasureID          
INNER JOIN tblparts P on d3.ProductID=P.PartsID AND HideonDelDocket <> 'T'                       
INNER JOIN tblclients c on d2.ClientID = c.ClientID               
LEFT JOIN tblrelatedparts AS d5 on (d3.ProductID=d5.ProductID AND d3.RelatedParentProductID=d5.ParentID)            
LEFT Join tblpartspics pp on pp.PartID = d3.ProductID  and pp.isdefault ='T'     
Left JOIN 
(SELECT 
  pqa.TransLineID ,  
  Sum(if(ifnull(pqad.CustFld6,0)=0 , pqad.uomqty *uom.weight , pqad.CustFld6)) AS GrossWeight,  
  Sum(if(ifnull(pqad.CustFld7,0)=0 , pqad.uomqty *uom.weight , pqad.CustFld7)) AS NetWeight  
  FROM tblpqa pqa   
  INNER JOIN tblpqadetails pqad ON pqa.pqaid = pqad.pqaid  AND pqad.PQAType ='Batch'  
  INNER JOIN tblunitsofmeasure uom ON pqa.UOMID = uom.UnitID  WHERE pqa.transtype in ('TSalesOrderLine' , 'TInvoiceLine')  
  GROUP BY pqa.TransLineID
) as WT on WT.TransLineID = d3.saleLineId   
WHERE d2.SaleID = d3.SaleID