{CompanyInfo}
SELECT  
CO.CompanyName, 
CO.Address, 
CO.Address2, 
CO.City, 
CO.State, 
CO.Postcode, 
CO.PhoneNumber AS PhoneNumber, 
CO.FaxNumber AS FaxNumber, 
CO.ABN, 
concat('Ph: ', CO.PhoneNumber) AS Phone, 
concat('Fax: ',  CO.FaxNumber) AS Fax, 
concat('Email: ',  CO.email) as EmailAddress, 
CO.URL,  
concat('Website: ', CO.URL) as WebAddress, 
concat_ws(', ',  nullif(CO.Address, ''),  nullif(CO.Address2, ''), nullif(CO.Address3, ''), nullif(CO.City ,  ''),  nullif(concat(CO.State ,  ' ' ,  CO.postCode  ),''),  nullif(CO.country ,  '') ) as CompAddress, 
concat_ws(', ',  nullif(CO.POBox ,  ''),  nullif(CO.POBox2 ,  ''), nullif(CO.POBox3 ,  ''), nullif(CO.POCity, ''),  nullif(concat(CO.POState, ' ' ,  CO.POPostcode),''),  nullif(CO.POCountry, '') ) as CompBillAddress,  
CO.email,  
'Admin .' as LoggedInUser    
FROM tblCompanyInformation AS CO    
~|||~{Details}
SELECT  
PO.SupplierName, 
PO.ClientPrintName as SupplierPrintName,
C.street as SuppStreet,  
C.street2 as SuppStreet2,  
C.street3 as SuppStreet3,  
C.suburb as SuppSuburb,  
C.state as SuppState,  
C.country as SuppCountry,   
C.postcode as SuppPostcode,   
SA.CompanyName as ShiptoCompanyName,
SA.ShipAddress,
SA.ShipAddress1,
SA.ShipCity,
SA.ShipPostCode,
SA.ShipState,
SA.ShipCountry, 
PO.ShipTo,
PO.OrderTo,  
PO.PurchaseOrderID,
PO.PurchaseOrderNumber,
PO.OriginalNo,
PO.TotalAmount,
PO.TotalAmountInc,
PO.EmployeeName,
PO.InvoiceNumber,
PO.ETADate,
PO.DueDate,
PO.Comments,
PO.SalesComments,
PO.Terms,
PO.Balance,
PO.Payment,
PO.AmountDue,
PO.EnteredBy,
PO.CustPONumber,
PO.ForeignExchangeCode,
PO.ForeignExchangeRate,
PO.ForeignTotalAmount,
PO.ForeignPaidAmount,
PO.ForeignBalanceAmount,
PO.ContactName,
PO.EquipmentName,  
POL.PurchaseLineID,
POL.PARTTYPE,
POL.ProductGroup,
POL.Product_Description,
POL.QtySold,
POL.UnitofMeasureQtySold,
POL.Shipped,
POL.UnitofMeasureShipped,
POL.BackOrder,
POL.UnitofMeasureBackorder,
POL.UnitofMeasurePOLines,
POL.UnitofMeasureMultiplier,
POL.Class,
POL.CustomerJob,
POL.TotalLineAmount,
POL.TotalLineAmountInc,
POL.LineTaxCode,
POL.LineTax,
POL.ReceivedDate,
POL.CustomField1,
POL.CustomField2,
POL.CustomField3,
POL.CustomField4,
POL.CustomField5,
POL.CustomField6,
POL.CustomField7,
POL.CustomField8,
POL.CustomField9,
POL.CustomField10,
POL.LineNotes,
POL.MemoLine,  
POL.ProductName,
POL.Product_Description,    
POL.QtySold * POL.LineCostInc as EstLineCostInc,    
POL.QtySold * POL.LineCost as EstCostEx,    
(((POL.QtySold) * POL.LineCostInc)-((POL.QtySold) * POL.LineCost)) as EstTax,     
UnitofMeasurePOLines,      
Concat("PL-",CONVERT(POL.PurchaseLineID, CHAR)) as PurchaseLineBarcode,
P.PURCHASEDESC_Memo as ProductPURCHASEDESC_Memo, 
P.CUSTFLD1 as ProductcustFld1,
P.CUSTFLD2 as ProductcustFld2,
P.CUSTFLD3  as ProductcustFld3,
P.CUSTFLD4 as ProductcustFld4,
P.CUSTFLD5 as ProductcustFld5,
P.CUSTFLD6 as ProductcustFld6,
P.CUSTFLD7 as ProductcustFld7,
P.CUSTFLD8 as ProductcustFld8,
P.CUSTFLD9 as ProductcustFld9,
P.CUSTFLD10 as ProductcustFld10,
P.CUSTFLD11 as ProductcustFld11,
P.CUSTFLD12 as ProductcustFld12,
P.CUSTFLD13 as ProductcustFld13,
P.CUSTDATE1 as ProductcustDate1,
P.CUSTDATE2 as ProductcustDate2,
P.CUSTDATE3 as ProductcustDate3, 
If(InStr(P.PRODUCTGROUP,'^') -1 >0,Left(P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')-1),P.PRODUCTGROUP) AS PartHeader,    
MID(P.PRODUCTGROUP, InStr(P.PRODUCTGROUP,'^')+1,   If(LOCATE('^',P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')+1) - InStr(P.PRODUCTGROUP,'^') >0,LOCATE('^',P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')+1)-1 - InStr(P.PRODUCTGROUP,'^'),  IF(InStr(P.PRODUCTGROUP,'^')<>0,CHAR_LENGTH(P.PRODUCTGROUP) - InStr(P.PRODUCTGROUP,'^'),0))) AS PartSubLevel1,    
If((LOCATE('^',P.PRODUCTGROUP,InStr(P.PRODUCTGROUP,'^')+1)) >0, MID(P.PRODUCTGROUP,  LOCATE('^',P.PRODUCTGROUP, InStr(P.PRODUCTGROUP,'^')+1)+1,CHAR_LENGTH(P.PRODUCTGROUP)- LOCATE('^',P.PRODUCTGROUP,  InStr(P.PRODUCTGROUP,'^')+1)),  Null)  AS PartSubLevel2,  
Barcode,
ProductCode,
pp.partpic,    
if(ifnull(POL.supplierProductCode,  '')<>'',  POL.supplierProductCode,  if(PO.SupplierName =  P.PREFEREDSUPP,    P.SupplierProductCode, '') )   as Supplier_ProductCode,  
P.PRODUCTCODE,P.ProductComment    , 
job.JobNumber,   
Job.Manufacture,  
Job.JobRegistration,  
Job.Colour,  
Job.BodyType,  
Job.SerialNumber as JobSerialNumber,  
Job.InsuranceCompanyName,   
Job.ExcessAmount, 
Job.CustomerJobNumber,  
C.BillStreet,  
C.BillStreet2,  
C.BillStreet3,  
C.BillSuburb,  
C.BillState,  
C.BillCountry,  
C.BillPostcode ,    
(POL.QtySold* POL.ForeignCurrencyLineCost) as EstForeingPrice ,   
(POL.QtySold* POL.ForeignCurrencyLineCost + POL.QtySold* POL.ForeignCurrencyLineCost * POL.LineTaxRate) as EstForeignPriceinc,  
(POL.QtySold* POL.LineTaxRate) as EstTax ,  
Uom.unitDEscription, 
uom.Weight,  
uom.NoOfBoxes,  
uom.Height,  
uom.Width,  
uom.Length,  
uom.Volume,  
e.WorkPhone   ,  
@LineCount := @LineCount + 1 AS LineCount   ,  
AmountToWords(PO.TotalAmount) as TotalAmountInWords ,  
AmountToWords(PO.TotalAmountInc) as TotalAmountIncInWords ,   
PQABatch.value as Batchno, 
PQABatch.expirydate,  
PQABatch.TruckLoadNo, 
PQABatch.UoMqty as BatchQty, 
PBin.Binlocation, 
PBin.binnumber, 
PQABins.uomqty as BinQty, 
PQASN.value as Serialnumber, 
ifnull(PQASN.UOMQty,  ifnull(PQABins.UOMQty,  ifnull(PQAbatch.UOMQty,  POL.UnitofMeasureShipped))) as AllocQty,  
C.ClientNo as SuppClientNo,
C.BankAccountName as SuppBankAccountName,
C.BankLodgementRef as SuppBankLodgementRef,
C.BankAccountBSB as SuppBankAccountBSB,
C.BankAccountNo as SuppBankAccountNo,
C.BankCode as SuppBankCode,
C.ABN as SuppABN  , 
POL.UnitOfMeasureMultiplier * POL.ForeignCurrencyLineCost as ForeignUOMLineCost, 
ifnull((UOM.Weight * POL.UnitofMeasureShipped), 0) as TotalUOM_Weight  
FROM  (SELECT @LineCount := 0) dummy,  tblPurchaseOrders PO  
INNER JOIN tblpurchaselines AS POL Using(PurchaseOrderID)                  
Inner JOIN tblparts P on ProductID=P.PartsID              
Left join tblPQA as PQA on PQA.transId = POL.PurchaseOrderID and PQA.translineId = POL.PurchaseLineID and PQA.transtype = 'TPurchaseOrderLine'  
left join tblPqaDetails PQABatch  on PQABatch.PQAId  = PQA.PQAID and PQABatch.PQAType = 'Batch'  and PQABatch.Active= 'T'      
left join tblPqaDetails PQABins  on PQABins.PQAId  = PQA.PQAID   and PQABins.PQAType = 'Bin' and PQABins.Active = 'T' and    ( (PQABatch.globalref = IFNULL(PQABins.ParentRef,'') and P.Batch='T'   and P.multiplebins = 'T') or (ifnull(PQABins.Parentref, '') = '' AND P.Batch='F' and P.multiplebins = 'T'))      
Left join tblProductBin PBin     on PBin.binId  = PQABins.BinID      
left join tblPqaDetails PQASN    on (PQASN.PQAId  = PQA.PQAID and PQASN.PQAType = 'SN'   and PQASN.Active = 'T'  and ((PQABatch.globalref = IFNULL(PQASN.ParentRef,'') and P.Batch='T' and P.multiplebins = 'F' and P.SNTracking = 'T')  or (PQAbins.Globalref = IFNULL(PQASn.ParentRef,'') and P.Multiplebins = 'T' and P.SNTracking = 'T') or  (ifnull(PQASN.Parentref, '') = '') and P.Batch='F' and P.Multiplebins = 'F' and P.SNTracking = 'T' ))       
INNER JOIN tblClients C on C.Company = PO.SupplierName                  
Left join tblshippingaddress SA on SA.ShipAddressID = PO.ShipToId  
inner join tblunitsofmeasure UOM on UOM.UnitID = POL.UnitOfMeasureID      
Left join tblclients job on job.clientId = POL.CustomerJobID 
Left join tblpartspics pp on ifnull(pp.Isdefault, '') = 'T' and pp.partID = P.PartsID  
Left join tblemployees e on e.EmployeeID = PO.EmployeeID    
~|||~{TaxDetails}
Select 
TTCL.`SubTaxCode`, 
TTCL.Percentage,  
Sum(TTCL.`TaxAmount`) as TaxAmount 
from tblpurchasetaxcodelines TTCL 
inner join tblpurchasetaxcodes TTC on TTCL.PurchaseTaxCodeID = TTC.ID    
~|||~{ClientCustomFields}
Select  
CFL.Description,  
CCV.Value 
from  tblpurchaseorders  Trans  
inner join tblcustomfieldvaluesClients CCV on Trans.ClientID = CCV.MasterID 
inner join tblcustomfieldlist CFL on CFL.CFID = CCV.CustomFieldlistId 
where ifnull(CCV.Value,'')<>''   and CFL.ListType = 'ltSupplier'    
~|||~{TransComments}
SELECT 
C.CommentsID,
C.Comments  
FROM tblComments C  
inner join tbltranscomments TC on C.CommentsID = TC.CommentID    
