program ErpServiceMenu;

uses
  ShareMem,
  Forms,
  frmConfigMain in 'frmConfigMain.pas' {fmConfigMain},
  frmServerConnect in 'frmServerConnect.pas' {fmServerConnect},
  JsonRpcConst in '..\JsonRPC\JsonRpcConst.pas',
  JsonRpcTcpClient in '..\JsonRPC\JsonRpcTcpClient.pas',
  ModuleUtils in '..\Modules\ModuleUtils.pas',
  ModuleInfoObj in '..\ModuleInfoObj.pas',
  ModuleBaseObj in '..\Modules\ModuleBaseObj.pas',
  ModuleConst in '..\Modules\ModuleConst.pas',
  ModuleFunctions in '..\ModuleFunctions.pas',
  ModuleBaseClientObj in '..\Modules\ModuleBaseClientObj.pas',
  ModuleMultisiteGuiObj in '..\Modules\Multisite\Gui\ModuleMultisiteGuiObj.pas',
  frmMultisiteConfigGui in '..\Modules\Multisite\Gui\frmMultisiteConfigGui.pas',
  ModuleUpdaterGuiObj in '..\Modules\Updater\Gui\ModuleUpdaterGuiObj.pas',
  frmModuleConfigBase in '..\Modules\frmModuleConfigBase.pas' {fmModuleConfigBase},
  frmUpdaterConfigGui in '..\Modules\Updater\Gui\frmUpdaterConfigGui.pas' {fmUpdaterConfigGui},
  ModuleClientServerGuiObj in '..\Modules\ClientServer\Gui\ModuleClientServerGuiObj.pas',
  frmClientServerConfigGui in '..\Modules\ClientServer\Gui\frmClientServerConfigGui.pas' {fmClientServerConfigGui},
  ModuleUserUtilsGuiObj in '..\Modules\UserUtils\Gui\ModuleUserUtilsGuiObj.pas',
  UserUtilsClientObj in '..\..\..\Dev\General\Objects\CommonObjects\UserUtilsClientObj.pas',
  ModalInputBoxGUI in '..\..\..\Dev\General\InputForms\ModalInputBoxGUI.pas' {fmModalInputBox},
  JSONObject in '..\..\..\Common\JSONObject.pas',
  JsonToObject in '..\..\..\Common\JsonToObject.pas',
  frmUserUtilsConfigGui in '..\Modules\UserUtils\Gui\frmUserUtilsConfigGui.pas' {fmUserUtilsConfigGui},
  JsonRpcBase in '..\JsonRPC\JsonRpcBase.pas',
  frmBaseEdit in '..\Modules\frmBaseEdit.pas',
  frmBase in '..\Modules\frmBase.pas' {fmBase},
  MultisiteConst in '..\Modules\Multisite\MultisiteConst.pas',
  MultisiteConfigObj in '..\Modules\Multisite\MultisiteConfigObj.pas',
  CipherUtils in '..\..\..\Common\CipherUtils.pas',
  frmServerEdit in '..\Modules\Multisite\Gui\frmServerEdit.pas',
  frmDatabaseEdit in '..\Modules\Multisite\Gui\frmDatabaseEdit.pas',
  frmRemoteDatabaseEdit in '..\Modules\Multisite\Gui\frmRemoteDatabaseEdit.pas',
  OpProgressObj in '..\..\..\Dev\General\Objects\CommonObjects\OpProgressObj.pas',
  ModuleWebAPIGuiObj in '..\Modules\WebAPI\Gui\ModuleWebAPIGuiObj.pas',
  frmWebAPIConfigGui in '..\Modules\WebAPI\Gui\frmWebAPIConfigGui.pas' {fmWebAPIConfigGui},
  LogThreadLib in '..\..\..\Dev\General\Objects\CommonObjects\LogThreadLib.pas',
  ModuleControl in '..\ModuleControl.pas',
  HTTPServerConfigObj in '..\HTTPServerConfigObj.pas',
  UtilsServerConfigObj in '..\UtilsServerConfigObj.pas',
  LogMessageTypes in '..\..\..\Dev\General\Objects\CommonObjects\LogMessageTypes.pas',
  LogThreadBase in '..\..\..\Dev\General\Objects\CommonObjects\LogThreadBase.pas',
  frmDatabaseBackup in '..\..\..\Dev\General\InputForms\frmDatabaseBackup.pas',
  SystemLib in '..\..\..\Dev\General\Objects\CommonObjects\SystemLib.pas',
  frmWebAPITestSteps in '..\Tester\frmWebAPITestSteps.pas',
  WebApiTestObj in '..\Tester\WebApiTestObj.pas',
  TesterObj in '..\Tester\TesterObj.pas',
  MySQLUtils in '..\..\..\Common\MySQLUtils.pas',
  DbConst in '..\..\..\Common\DbConst.pas',
  AppRunUtils in '..\..\..\Dev\General\Objects\CommonObjects\AppRunUtils.pas',
  SimpleEncrypt in '..\..\..\Common\SimpleEncrypt.pas',
  TestItemGUI in '..\Tester\TestItemGUI.pas' {TestItemFrame: TFrame},
  frmBaseTestSteps in '..\Tester\frmBaseTestSteps.pas',
  UtilsTestObj in '..\Tester\UtilsTestObj.pas',
  UtilsLib in '..\..\..\Common\UtilsLib.pas',
  ServerModuleStubObj in '..\..\..\Common\ServerModules\ServerModuleStubObj.pas',
  ModuleComms in '..\..\..\Common\ModuleComms.pas',
  SimplePipes in '..\..\..\Common\SimplePipes.pas',
  ThreadProperty in '..\..\..\Common\ThreadProperty.pas',
  ServerModuleConst in '..\..\..\Common\ServerModules\ServerModuleConst.pas',
  ModuleClientUtils in '..\Modules\ModuleClientUtils.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'ERP Service Menu';
  Application.CreateForm(TfmConfigMain, fmConfigMain);
  Application.Run;
end.
