library APIDLL;

uses
  ShareMem,
  ExcMagic,
  ExcMagicCON,
  SysUtils,
  Classes,
  windows,
  BusObjSales in '..\..\Dev\Sales\Objects\BusObjSales.pas',
  BusObjBase in '..\..\Dev\BaseClasses\Objects\BusObjBase.pas',
  UserLockObj in '..\..\Dev\General\Objects\CommonObjects\UserLockObj.pas',
  CommonLib in '..\..\Dev\General\Objects\CommonObjects\CommonLib.pas',
  CommonDbLib in '..\..\Dev\General\Objects\CommonObjects\CommonDbLib.pas',
  tcTypes in '..\..\Dev\General\Objects\CommonObjects\tcTypes.pas',
  AppDatabase in '..\..\Dev\General\Objects\AppDatabase.pas',
  DecimalRounding in '..\..\Dev\General\Objects\CommonObjects\DecimalRounding.pas',
  DNMAccessManager in '..\..\Dev\General\Objects\DNMAccessManager.pas',
  AccessLevelObj in '..\..\Dev\General\Objects\AccessLevelObj.pas',
  EmployeeObj in '..\..\Dev\Employee\Objects\EmployeeObj.pas',
  tcConst in '..\..\Dev\General\Objects\CommonObjects\tcConst.pas',
  tcClasses in '..\..\Dev\General\Objects\CommonObjects\tcClasses.pas',
  DNMLib in '..\..\Dev\General\Objects\CommonObjects\DNMLib.pas',
  ReceiptPrinterObj in '..\..\Dev\POS\Objects\ReceiptPrinterObj.pas',
  GuiPrefsObj in '..\..\Dev\General\Objects\GuiPrefsObj.pas',
  DataTreeObj in '..\..\Dev\General\Objects\CommonObjects\DataTreeObj.pas',
  ParserObj in '..\..\Dev\General\Objects\CommonObjects\ParserObj.pas',
  DbPrimaryKeysObj in '..\..\Dev\General\Objects\CommonObjects\DbPrimaryKeysObj.pas',
  CompanyPrefObj in '..\..\Dev\Utilities\Objects\CompanyPrefObj.pas',
  RegionalOptionsObj in '..\..\Dev\General\Objects\RegionalOptionsObj.pas',
  AuditTrailObj in '..\..\Dev\General\Objects\AuditTrailObj.pas',
  MergeObj in '..\..\Dev\General\Objects\MergeObj.pas',
  TransactionsTable in '..\..\Dev\Accounts\Objects\TransactionsTable.pas',
  TableFunctionsObj in '..\..\Dev\Utilities\Objects\TableFunctionsObj.pas',
  BranchObj in '..\..\Dev\General\Objects\BranchObj.pas',
  StockCostSystemsObj in '..\..\Dev\Inventory\Objects\StockCostSystemsObj.pas',
  tcDataUtils in '..\..\Dev\General\Objects\CommonObjects\tcDataUtils.pas',
  BusObjStock in '..\..\Dev\Inventory\Objects\BusObjStock.pas',
  BusObjGeneral in '..\..\Dev\BusinessObjects\BusObjGeneral.pas',
  LogLib in '..\..\Dev\General\Objects\CommonObjects\LogLib.pas',
  BusObjAudit in '..\..\Dev\BusinessObjects\BusObjAudit.pas',
  frmDelayMessageDlg in '..\..\Dev\General\InputForms\frmDelayMessageDlg.pas' {fmDelayMessageDlg},
  BusObjConst in '..\..\Dev\BusinessObjects\BusObjConst.pas',
  BusObjDataUtils in '..\..\Dev\BusinessObjects\BusObjDataUtils.pas',
  BusObjTaxCodes in '..\..\Dev\Accounts\Objects\BusObjTaxCodes.pas',
  BusobjProductProperties in '..\..\Dev\Inventory\Objects\BusobjProductProperties.pas',
  BusObjUtils in '..\..\Dev\BusinessObjects\BusObjUtils.pas',
  BusObjClass in '..\..\Dev\Accounts\Objects\BusObjClass.pas',
  BusObjTrans in '..\..\Dev\BaseClasses\Objects\BusObjTrans.pas',
  BusObjClient in '..\..\Dev\Clients\Common\Objects\BusObjClient.pas',
  BusObjCommon in '..\..\Dev\BusinessObjects\BusObjCommon.pas',
  DefaultClassObj in '..\..\Dev\General\Objects\DefaultClassObj.pas',
  ForeignExchangeObj in '..\..\Dev\Accounts\Objects\ForeignExchangeObj.pas',
  BusObjGLAccount in '..\..\Dev\Accounts\Objects\BusObjGLAccount.pas',
  BusObjPrintDoc in '..\..\Dev\BusinessObjects\BusObjPrintDoc.pas',
  BusobjSaleBase in '..\..\Dev\BaseClasses\Objects\BusObjSaleBase.pas',
  ClientDiscountObj in '..\..\Dev\Clients\Customers\Objects\ClientDiscountObj.pas',
  ProductPriceObj in '..\..\Dev\Inventory\Objects\ProductPriceObj.pas',
  GlobalEventsObj in '..\..\Dev\General\Objects\CommonObjects\GlobalEventsObj.pas',
  BusobjCash in '..\..\Dev\Sales\Objects\BusobjCash.pas',
  BusObjSmartOrder in '..\..\Dev\Purchases\Objects\BusObjSmartOrder.pas',
  busobjcompinfo in '..\..\Dev\Utilities\Objects\busobjcompinfo.pas',
  DNMExceptions in '..\..\Dev\General\Objects\DNMExceptions.pas',
  OptimiseInsertsObj in '..\..\Dev\General\Objects\OptimiseInsertsObj.pas',
  QueryManipulationObj in '..\..\Dev\General\Objects\QueryManipulationObj.pas',
  SysInfo in '..\..\Dev\General\Objects\CommonObjects\SysInfo.pas',
  BusObjPayRate in '..\..\Dev\Payroll\Objects\Pay\BusObjPayRate.pas',
  EmailUtils in '..\..\Dev\General\Objects\CommonObjects\EmailUtils.pas',
  PayPreferencesObj in '..\..\Dev\Payroll\Objects\Pay\PayPreferencesObj.pas',
  AppEnvironment in '..\..\Dev\General\Objects\CommonObjects\AppEnvironment.pas',
  AppXMLCmndProcObj in 'AppXMLCmndProcObj.pas',
  APIDllExportFunc in 'APIDllExportFunc.pas',
  ObjectFieldListObj in '..\..\Dev\General\Objects\CommonObjects\ObjectFieldListObj.pas',
  ExMagicUnit in 'ExMagicUnit.pas',
  busobjPOS in '..\..\Dev\POS\Objects\busobjPOS.pas',
  busobjPOSOrders in '..\..\Dev\POS\Objects\busobjPOSOrders.pas',
  BusObjPOSSale in '..\..\Dev\POS\Objects\BusObjPOSSale.pas',
  ClassExtenderListObj in '..\..\Dev\BaseClasses\Objects\ClassExtenderListObj.pas',
  BusObjAssessment in '..\..\Dev\Assessment\Objects\BusObjAssessment.pas',
  busobjPOSCustomize in '..\..\Dev\POS\Objects\busobjPOSCustomize.pas',
  FastFuncs in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\FastFuncs.pas',
  AnsiStringReplaceUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\AnsiStringReplaceUnit.pas',
  PosExUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\PosExUnit.pas',
  PosIExUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\PosIExUnit.pas',
  FastStringFuncs in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\FastStringFuncs.pas',
  FastStrings in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\FastStrings.pas',
  LowerCaseUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\LowerCaseUnit.pas',
  UpperCaseUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\UpperCaseUnit.pas',
  CompareTextUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\CompareTextUnit.pas',
  StrLenUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\StrLenUnit.pas',
  TrimUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\TrimUnit.pas',
  BusObjFCOnReport in '..\..\Dev\BaseClasses\Objects\BusObjFCOnReport.pas',
  BusObjTimeSheet in '..\..\Dev\Payroll\Objects\Pay\BusObjTimeSheet.pas',
  PayCommon in '..\..\Dev\Payroll\Objects\Pay\PayCommon.pas',
  PaySplitObj in '..\..\Dev\Payroll\Objects\Pay\PaySplitObj.pas',
  PayPaySplitsObj in '..\..\Dev\Payroll\Objects\Pay\PayPaySplitsObj.pas',
  ABAObj in '..\..\Dev\Accounts\Objects\ABAObj.pas',
  BaseInputForm in '..\..\Dev\BaseClasses\InputForms\BaseInputForm.pas' {BaseInputGUI},
  PrintTemplateObj in '..\..\Dev\TemplateReports\Objects\PrintTemplateObj.pas',
  ReportTemplates in '..\..\Dev\TemplateReports\Objects\ReportTemplates.pas',
  PersonalTabStops in '..\..\Dev\General\Objects\PersonalTabStops.pas',
  BaseFormForm in '..\..\Dev\BaseClasses\InputForms\BaseFormForm.pas' {BaseForm},
  MessageConst in '..\..\Dev\General\Objects\CommonObjects\MessageConst.pas',
  FormFactory in '..\..\Dev\General\Objects\FormFactory.pas',
  BaseListingForm in '..\..\Dev\BaseClasses\ListForms\BaseListingForm.pas' {BaseListingGUI},
  BusobjCustomFilter in '..\..\Dev\Utilities\Objects\BusobjCustomFilter.pas',
  frmSaveCustomFilter in '..\..\Dev\Utilities\InputForms\frmSaveCustomFilter.pas' {fmSaveCustomFilter},
  GlobalRefToIDToggleObj in '..\..\Dev\Utilities\Objects\GlobalRefToIDToggleObj.pas',
  ListSpeedHintGUI in '..\..\Dev\General\ListForms\ListSpeedHintGUI.pas',
  BaseHintForm in '..\..\Dev\BaseClasses\InputForms\BaseHintForm.pas' {BaseHintGUI},
  AppContextObj in '..\..\Dev\General\Objects\CommonObjects\AppContextObj.pas',
  StrToIntUnit in '..\..\Dev\General\Objects\CommonObjects\FastFuncs\StrToIntUnit.pas',
  SalesConst in '..\..\Dev\Sales\Objects\SalesConst.pas',
  BusObjPayBase in '..\..\Dev\Payroll\Objects\BusObjPayBase.pas',
  BusObjEmployeeDetails in '..\..\Dev\Payroll\Objects\BusObjEmployeeDetails.pas',
  BusObjWorkersCompensation in '..\..\Dev\Payroll\Objects\BusObjWorkersCompensation.pas',
  BusObjPayCommissionsBASE in '..\..\Dev\Payroll\Objects\BusObjPayCommissionsBASE.pas',
  BusObjEmployeepayrates in '..\..\Dev\Payroll\Objects\BusObjEmployeepayrates.pas',
  BusObjPaysPayratesBASE in '..\..\Dev\Payroll\Objects\BusObjPaysPayratesBASE.pas',
  BusObjpaysLeave in '..\..\Dev\Payroll\Objects\BusObjpaysLeave.pas',
  BusObjLeaveAccruals in '..\..\Dev\Payroll\Objects\BusObjLeaveAccruals.pas',
  BusObjEmployeePay in '..\..\Dev\Payroll\Objects\BusObjEmployeePay.pas',
  BusObjEmployeeLeave in '..\..\Dev\Payroll\Objects\BusObjEmployeeLeave.pas',
  BusObjEmployeePaySettings in '..\..\Dev\Payroll\Objects\BusObjEmployeePaySettings.pas',
  BusObjEmployeePaysplit in '..\..\Dev\Payroll\Objects\BusObjEmployeePaysplit.pas',
  BusObjEmployeeDeductions in '..\..\Dev\Payroll\Objects\BusObjEmployeeDeductions.pas',
  BusObjDeductions in '..\..\Dev\Payroll\Objects\BusObjDeductions.pas',
  BusObjSuperannuation in '..\..\Dev\Payroll\Objects\BusObjSuperannuation.pas',
  BusObjPensionBase in '..\..\Dev\Payroll\Objects\BusObjPensionBase.pas',
  BusObjfringeBenefitsTax in '..\..\Dev\Payroll\Objects\BusObjfringeBenefitsTax.pas',
  BusObjBenefitsBase in '..\..\Dev\Payroll\Objects\BusObjBenefitsBase.pas',
  BusObjEmployeeDocuments in '..\..\Dev\Employee\Objects\BusObjEmployeeDocuments.pas',
  BusObjPaysDeductions in '..\..\Dev\Payroll\Objects\BusObjPaysDeductions.pas',
  BusObjTaxBase in '..\..\Dev\Payroll\Objects\BusObjTaxBase.pas',
  BusObjTaxAUS in '..\..\Dev\Payroll\Objects\BusObjTaxAUS.pas',
  BusObjPaysPayratesAUS in '..\..\Dev\Payroll\Objects\BusObjPaysPayratesAUS.pas',
  BusObjEmpPaySettingsAUS in '..\..\Dev\Payroll\Objects\BusObjEmpPaySettingsAUS.pas',
  dmGUIStylers in '..\..\Dev\General\Module\dmGUIStylers.pas' {datGUIStylers: TDataModule},
  BusObjNDSBase in '..\..\Dev\BaseClasses\Objects\BusObjNDSBase.pas',
  SaveExcludeListObj in '..\..\Dev\BaseClasses\Objects\SaveExcludeListObj.pas',
  ClassFuncs in '..\..\Dev\General\Objects\CommonObjects\ClassFuncs.pas',
  BusObjEmployeeAllowances in '..\..\Dev\Payroll\Objects\BusObjEmployeeAllowances.pas',
  BusObjAllowances in '..\..\Dev\Payroll\Objects\BusObjAllowances.pas',
  BusObjPaysAllowances in '..\..\Dev\Payroll\Objects\BusObjPaysAllowances.pas',
  BusObjPayCommissionsAUS in '..\..\Dev\Payroll\Objects\BusObjPayCommissionsAUS.pas',
  BusObjPaysSuperannuation in '..\..\Dev\Payroll\Objects\BusObjPaysSuperannuation.pas',
  BusObjPaysDeductionsAUS in '..\..\Dev\Payroll\Objects\BusObjPaysDeductionsAUS.pas',
  BusObjPaysAllowancesAUS in '..\..\Dev\Payroll\Objects\BusObjPaysAllowancesAUS.pas',
  BusObjPayLeavesAUS in '..\..\Dev\Payroll\Objects\BusObjPayLeavesAUS.pas',
  Vista_MessageDlg in '..\..\Dev\General\Objects\CommonObjects\Vista_MessageDlg.pas',
  BusObjAppointments in '..\..\Dev\BusinessObjects\BusObjAppointments.pas',
  BusObjRepServices in '..\..\Dev\BusinessObjects\BusObjRepServices.pas',
  frmBinLocations in '..\..\Dev\Inventory\InputForms\frmBinLocations.pas' {fmbinLocations},
  BinLocationList in '..\..\Dev\Inventory\ListForms\BinLocationList.pas' {BinLocationListGUI},
  frmGeneralMessage in '..\..\Dev\General\InputForms\frmGeneralMessage.pas' {frmGeneralMessage},
  BusObjcommissionTypes in '..\..\Dev\Payroll\Objects\BusObjcommissionTypes.pas',
  busobjOrders in '..\..\Dev\Purchases\Objects\busobjOrders.pas',
  BusObjOrderBase in '..\..\Dev\BaseClasses\Objects\BusObjOrderBase.pas',
  busobjExpenses in '..\..\Dev\Purchases\Objects\busobjExpenses.pas',
  BusobjABA in '..\..\Dev\Accounts\Objects\BusobjABA.pas',
  busObjBankDepost in '..\..\Dev\Accounts\Objects\busObjBankDepost.pas',
  BusObjPaySundriesBASE in '..\..\Dev\Payroll\Objects\BusObjPaySundriesBASE.pas',
  BusObjPayPaysplits in '..\..\Dev\Payroll\Objects\BusObjPayPaysplits.pas',
  BusObjPayPaysplitsAUS in '..\..\Dev\Payroll\Objects\BusObjPayPaysplitsAUS.pas',
  BusObjPaySundriesAUS in '..\..\Dev\Payroll\Objects\BusObjPaySundriesAUS.pas',
  BusObjProdDescAttribute in '..\..\Dev\Inventory\Objects\BusObjProdDescAttribute.pas',
  CustomFilterList in '..\..\Dev\Utilities\ListForms\CustomFilterList.pas' {CustomFiltersListGUI},
  BusObjApprovals in '..\..\Dev\General\Objects\BusObjApprovals.pas',
  BusobjReconciliation in '..\..\Dev\Accounts\Objects\BusobjReconciliation.pas',
  BusObjAwards in '..\..\Dev\Payroll\Objects\BusObjAwards.pas',
  BusObjAwardsLeave in '..\..\Dev\Payroll\Objects\BusObjAwardsLeave.pas',
  BusObjAwardShifts in '..\..\Dev\Payroll\Objects\BusObjAwardShifts.pas',
  BusobjAwardClassificationDetail in '..\..\Dev\Payroll\Objects\BusobjAwardClassificationDetail.pas',
  BusObjClassificationAllowances in '..\..\Dev\Payroll\Objects\BusObjClassificationAllowances.pas',
  BusObjClassificationDeductions in '..\..\Dev\Payroll\Objects\BusObjClassificationDeductions.pas',
  BusObjClassificationExtraPayrates in '..\..\Dev\Payroll\Objects\BusObjClassificationExtraPayrates.pas',
  BusObjLeavetypes in '..\..\Dev\Payroll\Objects\BusObjLeavetypes.pas',
  frmBase in '..\..\Dev\BaseClasses\InputForms\frmBase.pas' {frmBaseGUI},
  MarketingLib in '..\..\Dev\Marketing\Objects\MarketingLib.pas',
  BusobjMarketingcontacts in '..\..\Dev\Marketing\Objects\BusobjMarketingcontacts.pas',
  BusObjMarketingLeads in '..\..\Dev\Marketing\Objects\BusObjMarketingLeads.pas',
  BusobjRangeSelection in '..\..\Dev\Marketing\Objects\BusobjRangeSelection.pas',
  EmailUtilsDefaultMailClient in '..\..\Dev\General\Objects\CommonObjects\EmailUtilsDefaultMailClient.pas',
  XMLDataObj in '..\..\Dev\General\Objects\XMLDataObj.pas' {XMLData: TDataModule},
  TransLockManagementObj in '..\..\Dev\Payments\Objects\TransLockManagementObj.pas',
  ReconciliationFlagsObj in '..\..\Dev\Payments\Objects\ReconciliationFlagsObj.pas',
  BusObjSimpleTypes in '..\..\Dev\General\Objects\CommonObjects\BusObjSimpleTypes.pas',
  APIDllExportFuncType in 'APIDllExportFuncType.pas',
  BusObjPaysTransactions in '..\..\Dev\Payroll\Objects\BusObjPaysTransactions.Pas',
  XMLRequestUtils in '..\..\Dev\General\Objects\CommonObjects\XMLRequestUtils.pas',
  XMLRequestConst in '..\..\Dev\General\Objects\CommonObjects\XMLRequestConst.pas',
  APIDllCmdProc in 'APIDllCmdProc.pas',
  LogThreadLib in '..\..\Dev\General\Objects\CommonObjects\LogThreadLib.pas',
  LogMessageTypes in '..\..\Dev\General\Objects\CommonObjects\LogMessageTypes.pas',
  MultiEventObj in '..\..\Dev\General\Objects\CommonObjects\MultiEventObj.pas',
  AccruedLeaveLiabilitiesAdj in '..\..\Dev\Payroll\Objects\AccruedLeaveLiabilitiesAdj.pas',
  AppVarsObj in '..\..\Dev\General\Objects\CommonObjects\AppVarsObj.pas',
  ColoursPrefsObj in '..\..\Dev\General\Objects\ColoursPrefsObj.pas',
  BusObjRep in '..\..\Dev\Employee\Objects\BusObjRep.pas',
  ProductQtyLib in '..\..\Dev\Inventory\Module\ProductQtyLib.pas',
  busobjPQA in '..\..\Dev\Inventory\Objects\busobjPQA.pas',
  busobjStockMovement in '..\..\Dev\Inventory\Objects\busobjStockMovement.pas',
  BusObjProductbin in '..\..\Dev\Inventory\Objects\BusObjProductbin.pas',
  BusObjProcTreePart in '..\..\Dev\Manufacturing\Objects\BusObjProcTreePart.pas',
  BusObjProcess in '..\..\Dev\Manufacturing\Objects\BusObjProcess.pas',
  BusObjProcessPartNDS in '..\..\Dev\Manufacturing\Objects\BusObjProcessPartNDS.pas',
  BusObjProcessStep in '..\..\Dev\Manufacturing\Objects\BusObjProcessStep.pas',
  BusObjProcessTimeNDS in '..\..\Dev\Manufacturing\Objects\BusObjProcessTimeNDS.pas',
  ProcessDataUtils in '..\..\Dev\Manufacturing\Objects\ProcessDataUtils.pas',
  BusObjProcPrefs in '..\..\Dev\Manufacturing\Objects\BusObjProcPrefs.pas',
  BusObjNDSGenDb in '..\..\Dev\BaseClasses\Objects\BusObjNDSGenDb.pas',
  BusObjAccountPosting in '..\..\Dev\Accounts\Objects\BusObjAccountPosting.pas',
  BusObjAccountPostingDetail in '..\..\Dev\Accounts\Objects\BusObjAccountPostingDetail.pas',
  BusobjStockAdjustEntry in '..\..\Dev\Inventory\Objects\BusobjStockAdjustEntry.pas',
  DataTreeBaseObj in '..\..\Dev\General\Objects\CommonObjects\DataTreeBaseObj.pas',
  XMLFuncLib in '..\..\Dev\General\Objects\CommonObjects\XMLFuncLib.pas',
  IntegerListObj in '..\..\Dev\General\Objects\CommonObjects\IntegerListObj.pas',
  BusObjPublicHolidays in '..\..\Dev\General\Objects\CommonObjects\BusObjPublicHolidays.Pas',
  frmBinLocation in '..\..\Dev\Inventory\InputForms\frmBinLocation.pas' {fmbinLocation},
  BusobjAttribProduct in '..\..\Dev\Inventory\Objects\BusobjAttribProduct.pas',
  BusobjProdAttribGroup in '..\..\Dev\Inventory\Objects\BusobjProdAttribGroup.pas',
  busobjstockTransferentry in '..\..\Dev\Inventory\Objects\busobjstockTransferentry.pas',
  (*BusObjExchangeRate in '..\..\Dev\BaseClasses\Objects\BusObjExchangeRate.pas',*)
  CustomFieldConfigObj in '..\..\Dev\General\Objects\CustomFieldConfigObj.pas',
  frmImportoptionsFrm in '..\..\Dev\General\InputForms\frmImportoptionsFrm.pas' {frmImportoptions},
  BusObjImportExport in '..\..\Dev\General\Objects\CommonObjects\BusObjImportExport.pas',
  busobjdirty in '..\..\Dev\General\Objects\BusobjDirty.Pas',
  BusObjEquipment in '..\..\Dev\Equipment\Objects\BusObjEquipment.pas',
  busobjrepairs in '..\..\Dev\Repairs\Objects\BusObjRepairs.pas',
  BusObjShipContainerDetails in '..\..\Dev\Purchases\Objects\BusObjShipContainerDetails.Pas',
  BusObjShippingContainer in '..\..\Dev\Purchases\Objects\BusObjShippingContainer.Pas',
  UserUtilsClientObj in '..\..\Dev\General\Objects\CommonObjects\UserUtilsClientObj.pas',
  SoundObj in '..\..\Dev\General\Objects\SoundObj.pas',
  JsonRpcBase in '..\ERPUtilsServer\JsonRPC\JsonRpcBase.pas',
  JsonRpcConst in '..\ERPUtilsServer\JsonRPC\JsonRpcConst.pas',
  JsonRpcTcpClient in '..\ERPUtilsServer\JsonRPC\JsonRpcTcpClient.pas',
  BusobjBranch in '..\..\Dev\General\Objects\BusobjBranch.Pas',
  BusObjProductPicture in '..\..\Dev\Inventory\Objects\BusObjProductPicture.pas',
  busobjProductcommission in '..\..\Dev\Inventory\Objects\busobjProductcommission.Pas',
  BusobjSalesCommission in '..\..\Dev\Employee\Objects\BusobjSalesCommission.Pas',
  CalcSalescommission in '..\..\Dev\Employee\Objects\CalcSalescommission.pas',
  busobjSerialnumbers in '..\..\Dev\Inventory\Objects\busobjSerialnumbers.Pas',
  frmDesigner in '..\..\Dev\TemplateReports\InpuForms\frmDesigner.pas' {fmDesigner},
  BusObjCurrency in '..\..\Dev\BaseClasses\Objects\BusObjCurrency.pas',
  MonitorTransactionEvents in '..\..\Dev\General\Objects\MonitorTransactionEvents.pas',
  BusObjRewardPoints in '..\..\Dev\Clients\Customers\Objects\BusObjRewardPoints.pas',
  DataImport in '..\..\Dev\General\Objects\DataImport.pas';

{$R *.res}

procedure EntryPointFunc(Reason:integer);
begin
  case reason of
    DLL_PROCESS_ATTACH:
      begin

      end;
    DLL_THREAD_ATTACH:
      begin

        IsMultiThread := true;
      end;
    DLL_PROCESS_DETACH:
      begin

      end;
    DLL_THREAD_DETACH:
      begin

      end;
  else

  end;
end;


exports
//  ProcessXMLRequest,
  Execute,
  OpenCompany,
  CloseCompany,
  GetBusobj,
  OpenForUser,
  CurConnection,
//  ProcessXML,
//  ProcessXMLRequestNode,
  GetClassPropertyList;

begin
  DLLProc := @EntryPointFunc;
end.
